/* This file is generated by scripts/build-study-data.py. */
/* Do not edit this file directly; edit content/courses/* instead. */
window.studyLibrary = {
  "generatedAt": "2026-03-31T05:25:49.875689+00:00",
  "courseOrder": [
    "linux-programming",
    "multicultural-understanding"
  ],
  "courses": [
    {
      "id": "linux-programming",
      "meta": {
        "title": "리눅스 프로그래밍 시험 강의 노트",
        "summary": "Desktop/리눅스프로그래밍 폴더의 강의 PDF 7개를 바탕으로, 운영체제 개념부터 VIM, 파일·디렉터리, 권한, 파이프까지 시험 대비용 설명으로 다시 엮은 학습 사이트다. 목적은 슬라이드를 그냥 읽는 것이 아니라, '왜 이 명령을 쓰는지'와 '시험에서 어떻게 설명해야 하는지'를 한 번에 잡는 것이다.",
        "courseLabel": "리눅스 프로그래밍",
        "quickGuideLabel": "VIM Survival",
        "quickGuideTitle": "VIM을 한 번에 잡는 생존 매뉴얼",
        "atlasLabel": "Command Atlas",
        "atlasTitle": "명령어 아틀라스",
        "atlasFilterPlaceholder": "예: grep, chmod, :wq, pipe",
        "drillLabel": "Drills",
        "drillTitle": "실전 대비 문제 루틴",
        "lectureDetailMiniLabel": "Commands",
        "lectureDetailTitle": "시험용 명령어 해설",
        "lectureSyntaxLabel": "기본 형식",
        "lectureExampleLabel": "예시",
        "lectureDetailEmpty": "아직 이 강의의 명령어 해설이 작성되지 않았습니다.",
        "statsLectureCards": "강의 해설 명령",
        "statsAtlasItems": "핵심 명령 묶음",
        "courseId": "linux-programming",
        "sources": [
          {
            "file": "lec2-4471013 Linux basic.pdf",
            "pages": 33
          },
          {
            "file": "lec3-4471013 editor I.pdf",
            "pages": 22
          },
          {
            "file": "lec4-4471013-editor II.pdf",
            "pages": 25
          },
          {
            "file": "lec4-practice-4471013-vim.pdf",
            "pages": 7
          },
          {
            "file": "lec5-4471013-editor III and more commands.pdf",
            "pages": 40
          },
          {
            "file": "lec5-practice-4471013-more commands I.pdf",
            "pages": 7
          },
          {
            "file": "lec6-4471013-file and dir.pdf",
            "pages": 45
          }
        ],
        "generatedAt": "2026-03-31T05:25:49.875689+00:00",
        "authoredLectureCount": 7,
        "draftLectureCount": 0
      },
      "fastRecall": [
        "Operating System은 하드웨어와 응용 프로그램 사이에서 자원을 관리하는 소프트웨어다.",
        "Shell은 사용자의 명령을 해석해서 kernel에 전달하는 command interpreter다.",
        "VIM에서는 입력한 글자가 바로 디스크에 저장되지 않고 editing buffer에 먼저 반영된다.",
        "파이프는 앞 명령의 <code>stdout</code>을 뒤 명령의 <code>stdin</code>으로 연결한다.",
        "권한 숫자 755는 <code>rwx r-x r-x</code>, 644는 <code>rw- r-- r--</code>로 읽는다.",
        "<code>rm -rf</code>는 되돌리기 어려우므로 경로를 두 번 확인하고 실행해야 한다."
      ],
      "examMap": [
        {
          "title": "운영체제는 '자원 관리자'로 설명하라",
          "body": "슬라이드는 OS를 단순한 프로그램 묶음이 아니라 메모리, 프로세스, 장치, 파일 시스템을 관리하는 층으로 설명한다. 시험 답안에서는 '사용자에게는 프로그램 실행 환경, 프로그래머에게는 이해해야 하는 시스템'이라고 정리하면 강의 흐름과 맞는다."
        },
        {
          "title": "Linux 이해의 중심은 Shell과 Kernel의 분리다",
          "body": "사용자는 shell prompt에서 명령을 입력하고, shell이 이를 해석해 kernel과 상호작용한다. 그래서 <code>login → shell prompt → command → kernel/service</code> 흐름을 머릿속에 넣어두면 명령어 문제와 구조 문제를 같이 푼다."
        },
        {
          "title": "VIM은 모드 기반 편집기라는 점이 핵심이다",
          "body": "초보자가 가장 헷갈리는 지점은 '왜 타이핑했는데 글자가 안 써지지?'다. 이유는 기본이 command mode이기 때문이다. 입력은 input mode에서 하고, 편집 제어는 command mode에서 한다는 문장을 바로 말할 수 있어야 한다."
        },
        {
          "title": "파일 시스템 문제는 경로와 권한을 동시에 본다",
          "body": "상대 경로와 절대 경로, 파일/디렉터리 차이, <code>cd</code>·<code>mv</code>·<code>cp</code>·<code>rm</code>, 그리고 <code>rwx</code> 권한 구조가 한 묶음이다. 명령 자체보다 '무엇을 누구에게 허용하는가'가 답의 중심이다."
        },
        {
          "title": "리다이렉션과 파이프는 입출력 흐름으로 외워라",
          "body": "<code>&gt;</code>, <code>&gt;&gt;</code>, <code>&lt;</code>, <code>|</code>, <code>tee</code>는 문법 암기보다 데이터가 어디로 흐르는지로 이해해야 한다. 같은 내용을 '화면에만', '파일에만', '둘 다'로 구분하면 헷갈림이 줄어든다."
        },
        {
          "title": "실습 PDF는 시험용 손동작을 고정하는 용도다",
          "body": "실습 자료는 새로운 이론보다는 손이 먼저 움직이도록 만드는 자료다. VIM에서 줄 삭제, 붙여넣기, 치환을 반복하고, 쉘에서는 옵션 확인과 계산, 파일 조작을 해 보면서 답을 자동화하는 데 의미가 있다."
        }
      ],
      "cramPlan": [
        {
          "time": "0-15분",
          "title": "운영체제 / Shell 틀 잡기",
          "body": "<code>OS → kernel → shell → command</code> 구조, 로그인과 프롬프트 의미, <code>date</code>·<code>who</code>·<code>man</code>의 차이를 먼저 정리한다."
        },
        {
          "time": "15-35분",
          "title": "VIM 모드와 편집 동작",
          "body": "<code>i/a/o</code>, <code>Esc</code>, <code>:wq</code>, 이동, 삭제, 복사, 붙여넣기, 치환을 한 세트로 복습한다. 특히 <code>p/P</code>, <code>u/.</code>, <code>yy/dd</code>의 의미를 말로 설명할 수 있어야 한다."
        },
        {
          "time": "35-50분",
          "title": "파일 / 디렉터리 / 권한",
          "body": "상대 경로와 절대 경로, <code>cd</code>/<code>pwd</code>/<code>mkdir</code>/<code>mv</code>/<code>cp</code>/<code>rm</code>, <code>755</code>와 <code>644</code> 해석을 집중 복습한다."
        },
        {
          "time": "50-60분",
          "title": "파이프 / 리다이렉션 / 자주 나오는 비교",
          "body": "<code>cat</code> vs <code>more</code>, <code>grep</code> vs <code>find</code>, <code>who</code> vs <code>w</code> vs <code>whoami</code>, <code>&gt;</code> vs <code>&gt;&gt;</code> vs <code>| tee</code>를 마지막으로 정리한다."
        }
      ],
      "vimCheat": [
        {
          "title": "모드 전환",
          "bullets": [
            "<code>i</code>: 현재 커서 앞에서 입력 시작",
            "<code>a</code>: 현재 커서 뒤에서 입력 시작",
            "<code>o</code>/<code>O</code>: 현재 줄 아래/위에 새 줄 만들고 입력",
            "<code>Esc</code>: 언제든 command mode로 복귀",
            "<code>:w</code>, <code>:q</code>, <code>:q!</code>, <code>:wq</code>, <code>ZZ</code>는 저장/종료 계열 명령"
          ]
        },
        {
          "title": "이동",
          "bullets": [
            "<code>h j k l</code>: 좌 하 상 우",
            "<code>0</code>, <code>^</code>, <code>$</code>: 줄 시작, 공백 제외 첫 문자, 줄 끝",
            "<code>w</code>, <code>b</code>: 다음 단어 시작, 이전 단어 시작",
            "<code>gg</code>, <code>G</code>, <code>:n</code>, <code>nG</code>: 파일/줄 단위 점프",
            "<code>Ctrl+F/B/D/U</code>: 한 화면 또는 반 화면 단위 스크롤"
          ]
        },
        {
          "title": "수정 / 삭제 / 복사",
          "bullets": [
            "<code>r</code>: 현재 문자 1개 덮어쓰기",
            "<code>R</code>, <code>s</code>, <code>C</code>, <code>cc</code>, <code>cw</code>: 내용 바꾸기 계열",
            "<code>x</code>, <code>X</code>, <code>D</code>, <code>dd</code>: 삭제 계열",
            "<code>yy</code>, <code>nY</code>, <code>:from,to y</code>: 줄 복사",
            "<code>p</code>/<code>P</code>: 뒤에 붙여넣기 / 앞에 붙여넣기"
          ]
        },
        {
          "title": "검색 / 치환",
          "bullets": [
            "<code>/pattern</code>, <code>n</code>, <code>N</code>: 검색과 다음/이전 결과 이동",
            "<code>^</code>, <code>$</code>, <code>\\&lt;</code>, <code>\\&gt;</code>: 라인/단어 경계",
            "<code>[0-9]</code>, <code>[^0-9]</code>, <code>\\d</code>, <code>\\s</code>, <code>.</code>: 문자 클래스",
            "<code>:%s/pattern/string/g</code>: 전체 범위 치환",
            "<code>c</code>, <code>i</code>, <code>I</code>, <code>g</code> 옵션의 의미를 꼭 기억"
          ]
        }
      ],
      "commandAtlas": [
        {
          "title": "시스템 상태와 사용자",
          "items": [
            {
              "name": "date",
              "use": "현재 날짜와 시간을 본다. <code>-u</code>는 UTC 기준.",
              "compare": "시간 자체 확인용. 사용자 정보와는 무관하다.",
              "example": "date -u"
            },
            {
              "name": "users / who / w / whoami / id",
              "use": "로그인 사용자와 자신의 계정 정보를 본다.",
              "compare": "<code>users</code>는 단순 이름, <code>who</code>는 로그인 정보, <code>w</code>는 현재 작업 포함, <code>whoami</code>는 나 자신, <code>id</code>는 UID/GID까지.",
              "example": "who\nw\nid"
            },
            {
              "name": "hostname / uname",
              "use": "호스트 이름과 시스템 정보를 확인한다.",
              "compare": "호스트 식별 vs 시스템/커널 정보로 구분.",
              "example": "hostname\nuname -a"
            },
            {
              "name": "last",
              "use": "과거 로그인 기록을 확인한다.",
              "compare": "현재 로그인만 보는 <code>who</code>와 대비된다.",
              "example": "last"
            }
          ]
        },
        {
          "title": "파일 탐색과 내용 보기",
          "items": [
            {
              "name": "ls",
              "use": "파일과 디렉터리 목록을 본다.",
              "compare": "<code>-l</code> 긴 형식, <code>-a</code> 숨김 포함, <code>-t</code> 수정 시간, <code>-R</code> 재귀.",
              "example": "ls -la"
            },
            {
              "name": "cat / more / head / tail",
              "use": "파일 내용을 보는 계열.",
              "compare": "전체 출력, 화면 단위, 앞부분, 뒷부분으로 역할을 나눈다.",
              "example": "head -n 20 main.c\ntail -n 50 app.log"
            },
            {
              "name": "file",
              "use": "대상의 파일 종류를 확인한다.",
              "compare": "내용을 출력하지 않고 타입을 판별한다.",
              "example": "file a.out"
            }
          ]
        },
        {
          "title": "파일 / 디렉터리 조작",
          "items": [
            {
              "name": "cd / pwd",
              "use": "현재 작업 디렉터리 이동과 확인.",
              "compare": "<code>cd</code>는 상태 변경, <code>pwd</code>는 현재 상태 확인.",
              "example": "cd ~/course/linux\npwd"
            },
            {
              "name": "mkdir / rmdir",
              "use": "디렉터리 생성과 삭제.",
              "compare": "<code>rmdir</code>는 비어 있을 때만 안전하게 삭제 가능.",
              "example": "mkdir /home/${USER}/course/linux"
            },
            {
              "name": "mv / cp / rm",
              "use": "이동(또는 이름 변경), 복사, 삭제.",
              "compare": "<code>mv</code>는 rename 가능, <code>cp -r</code>는 디렉터리 복사, <code>rm -r</code>는 재귀 삭제.",
              "example": "mv report.txt old_report.txt\ncp -r dir1 dir2\nrm -i note.txt"
            },
            {
              "name": "alias",
              "use": "자주 쓰는 명령에 별칭을 붙인다.",
              "compare": "보통 <code>.bashrc</code>에 넣어 자동 로드한다.",
              "example": "alias ll='ls -l'"
            }
          ]
        },
        {
          "title": "검색과 정리",
          "items": [
            {
              "name": "grep",
              "use": "파일 내용에서 패턴이 있는 줄을 찾는다.",
              "compare": "<code>find</code>와 달리 내용 기반 검색이다.",
              "example": "grep -n \"from\" file2"
            },
            {
              "name": "find",
              "use": "이름 패턴으로 파일과 디렉터리를 찾는다.",
              "compare": "내용이 아니라 경로/이름을 찾는다.",
              "example": "find . -iname \"*.txt\""
            },
            {
              "name": "sort / wc / split",
              "use": "정렬, 개수 세기, 파일 분할.",
              "compare": "<code>sort -n</code> 숫자 정렬, <code>wc -l</code> 줄 수, <code>split -l</code> 행 단위 분할.",
              "example": "sort -n scores.txt\nwc -l main.c\nsplit -l 1000 big.txt part_"
            }
          ]
        },
        {
          "title": "권한과 셸 입출력",
          "items": [
            {
              "name": "chmod",
              "use": "파일/디렉터리 권한을 수정한다.",
              "compare": "숫자 모드와 기호 모드를 둘 다 이해해야 한다.",
              "example": "chmod 755 run.sh\nchmod u+x run.sh"
            },
            {
              "name": "> / >> / <",
              "use": "출력 덮어쓰기, 출력 추가, 입력 리다이렉션.",
              "compare": "모두 파일과 연결된다. 프로그램 연결은 파이프가 담당한다.",
              "example": "cat file1 > file2\nsort < unsorted"
            },
            {
              "name": "| / tee",
              "use": "앞 명령의 출력이 뒤 명령의 입력으로 들어간다.",
              "compare": "<code>tee</code>는 흐름을 유지하면서 파일 저장까지 한다.",
              "example": "ls | grep file\nsort < unsorted | tee sorted"
            },
            {
              "name": "history",
              "use": "이전에 실행한 명령을 확인하고 재사용한다.",
              "compare": "<code>!!</code>는 직전 명령, <code>!n</code>은 n번째 명령 재실행.",
              "example": "history 20\n!!"
            }
          ]
        },
        {
          "title": "VIM 핵심 명령",
          "items": [
            {
              "name": "입력/저장",
              "use": "<code>i</code>, <code>a</code>, <code>o</code>, <code>Esc</code>, <code>:wq</code>로 편집의 기본 루프를 만든다.",
              "compare": "입력 모드 진입 위치와 종료 동작 차이를 이해해야 한다.",
              "example": "ihello<Esc>\n:wq"
            },
            {
              "name": "이동",
              "use": "<code>h j k l</code>, <code>0</code>, <code>$</code>, <code>w</code>, <code>b</code>, <code>gg</code>, <code>G</code>로 위치를 제어한다.",
              "compare": "문자, 단어, 줄, 파일 범위를 넘나드는 이동 계열이다.",
              "example": "gg\n42G\n$"
            },
            {
              "name": "편집",
              "use": "<code>cw</code>, <code>cc</code>, <code>x</code>, <code>dd</code>, <code>yy</code>, <code>p</code>, <code>u</code>, <code>.</code>",
              "compare": "삭제/복사/붙여넣기 모두 버퍼를 공유한다.",
              "example": "yy\np\nu\n."
            },
            {
              "name": "검색/치환",
              "use": "<code>/pattern</code>, <code>n</code>, <code>N</code>, <code>:%s/old/new/g</code>",
              "compare": "검색 결과 이동과 범위 치환을 묶어서 이해해야 한다.",
              "example": "/linux\n:%s/Linux/linux/g"
            }
          ]
        }
      ],
      "studyDrills": [
        {
          "title": "서술형 1분 답안 훈련",
          "body": "아래 문장을 소리 내어 3번 말하면 운영체제/셸/권한 문제에서 문장 틀이 잡힌다.",
          "bullets": [
            "Shell은 사용자의 명령을 해석해 kernel에 전달하는 command interpreter다.",
            "VIM의 기본 모드는 command mode이고, 입력은 input mode에서 수행한다.",
            "파일 권한은 owner, group, others에 대해 read, write, execute를 각각 부여한다."
          ]
        },
        {
          "title": "VIM 손 루틴",
          "body": "빈 파일에서 아래 순서로 5번 반복한다. 멈춤 없이 이어지는지가 중요하다.",
          "bullets": [
            "<code>vim test.txt</code>로 열기",
            "<code>i</code>로 입력하고 <code>Esc</code>로 나오기",
            "<code>yy</code>, <code>p</code>, <code>dd</code>, <code>u</code> 순서 연습",
            "<code>:%s/old/new/g</code> 한 번 수행 후 <code>:wq</code>"
          ]
        },
        {
          "title": "파일 시스템 확인 루틴",
          "body": "경로와 권한은 머리보다 손으로 확인하는 편이 오래 간다.",
          "bullets": [
            "<code>pwd</code>로 현재 위치 확인",
            "<code>mkdir</code>와 <code>cd</code>로 하위 구조 만들기",
            "<code>ls -l</code>로 권한 읽기",
            "<code>chmod 755</code>와 <code>chmod u+x</code>를 비교 적용하기"
          ]
        },
        {
          "title": "파이프 / 리다이렉션 구별 문제",
          "body": "아래 둘의 차이를 설명할 수 있으면 입출력 문제는 거의 정리된다.",
          "bullets": [
            "<code>cat file &gt; out.txt</code>: 출력이 파일로 간다.",
            "<code>cat file | more</code>: 출력이 다음 프로그램의 입력으로 간다.",
            "<code>sort &lt; unsorted | tee sorted</code>: 화면에도 보이고 파일에도 저장된다."
          ]
        }
      ],
      "lectures": [
        {
          "order": 1,
          "status": "ready",
          "id": "lec2",
          "badge": "Lec 2",
          "type": "core",
          "title": "운영체제와 Linux 기본기",
          "source": "lec2-4471013 Linux basic.pdf",
          "theme": "OS / 계정 / 기본 명령",
          "summary": "운영체제가 무엇을 하는지, Linux가 어떤 역사와 구조를 갖는지, 그리고 로그인 후 어떤 기본 명령으로 시스템과 상호작용하는지 잡아 주는 시작 강의다.",
          "narrative": [
            "이 강의의 핵심은 Linux를 '명령어 모음'이 아니라 '운영체제 위에서 돌아가는 환경'으로 이해하게 만드는 데 있다. 슬라이드는 운영체제를 자원 관리자라고 부른다. 즉 CPU, 메모리, 장치, 파일 시스템 같은 자원을 여러 사용자와 프로그램이 충돌 없이 쓰게 해 주는 층이다.",
            "또 하나의 줄기는 UNIX에서 Linux로 이어지는 역사다. 이 부분은 연도 암기보다 왜 Linux가 널리 쓰이는지 설명할 수 있으면 충분하다. 다중 사용자, 이식성, 계층 구조, 쉘과 커널의 분리 같은 특징이 현재 Linux 사용성의 이유가 된다.",
            "실전에서는 로그인 이후 보게 되는 shell prompt와 기본 명령의 역할을 이해해야 한다. 사용자는 shell에 명령을 입력하고, shell은 이를 해석해 kernel이 수행하도록 연결한다. 그래서 <code>date</code>, <code>who</code>, <code>ls</code>, <code>man</code> 같은 명령도 단순 기능이 아니라 '시스템 상태를 읽는 인터페이스'로 보는 것이 맞다."
          ],
          "concepts": [
            {
              "title": "Operating System의 정의",
              "body": "OS는 응용 프로그램이 실행될 수 있는 기반을 제공하고, 동시에 메모리 관리, 프로세스 관리, 장치 관리, 파일 시스템 관리를 담당한다. 시험에서는 '하드웨어 위에서 응용 프로그램과 사용자를 연결하는 자원 관리자'라고 정리하면 안정적이다."
            },
            {
              "title": "Kernel과 Shell의 역할 분리",
              "body": "Kernel은 실제 자원 관리의 중심이고, shell은 사용자의 명령을 읽고 해석하는 명령 해석기다. 사용자가 직접 kernel에 말하는 것이 아니라 shell을 통해 커널 서비스를 요청한다."
            },
            {
              "title": "계정과 로그인",
              "body": "Linux 계정은 ID와 비밀번호로 식별되며, 로그인은 시스템 사용 권한을 얻는 과정이다. 로그인 뒤에는 사용자 환경이 구성되고 shell prompt가 나타난다."
            },
            {
              "title": "기본 명령의 묶음",
              "body": "시간 확인, 접속 사용자 확인, 파일 목록 확인, 파일 내용 보기, 비밀번호 변경, 로그인 기록, 도움말 확인, 명령 위치 확인, 호스트/시스템 정보 확인이 한 세트다. 명령 자체보다 '무슨 종류의 정보를 보는가'로 분류해 외우면 오래 간다."
            }
          ],
          "commands": [
            {
              "name": "date / who / last",
              "syntax": "date [-u]\nwho\nlast",
              "idea": "현재 시간, 현재 로그인 사용자, 과거 로그인 기록을 보는 기본 계열이다.",
              "example": "date\nwho\nlast",
              "pitfall": "<code>who</code>는 '지금 누가 로그인 중인지', <code>last</code>는 '과거 로그인 이력'이라는 차이를 구분해야 한다."
            },
            {
              "name": "ls / cat / more",
              "syntax": "ls\ncat file\nmore file",
              "idea": "<code>ls</code>는 목록, <code>cat</code>은 작은 파일의 전체 출력, <code>more</code>는 긴 파일을 화면 단위로 보는 데 적합하다.",
              "example": "ls -l\ncat notes.txt\nmore very_long.txt",
              "pitfall": "큰 파일을 한 번에 읽을 때는 <code>cat</code>보다 <code>more</code>가 낫다. 시험에서 용도 비교 문제가 자주 나온다."
            },
            {
              "name": "passwd / man / info / whatis",
              "syntax": "passwd\nman ls\ninfo ls\nwhatis ls",
              "idea": "설정 변경과 도움말 계열 명령이다. 깊이는 <code>man</code>이 가장 일반적이고, <code>whatis</code>는 짧은 한 줄 설명에 가깝다.",
              "example": "passwd\nman hostname\nwhatis uname",
              "pitfall": "<code>whatis</code>는 명령의 존재 설명이고, 상세 사용법은 <code>man</code>이나 <code>info</code>를 봐야 한다."
            },
            {
              "name": "which / hostname / uname",
              "syntax": "which ls\nhostname\nuname",
              "idea": "명령 위치, 호스트 이름, 시스템 정보를 보는 계열이다.",
              "example": "which vim\nhostname\nuname -a",
              "pitfall": "<code>which</code>는 실행 파일 위치를 보여줄 뿐 명령 설명까지는 하지 않는다."
            }
          ],
          "pitfalls": [
            "운영체제를 응용 프로그램과 같은 수준으로 설명하면 안 된다. 한 단계 아래에서 자원을 관리하는 층이다.",
            "Shell prompt는 단순 장식이 아니라 '명령을 받을 준비가 된 상태'를 뜻한다.",
            "<code>exit</code>와 <code>logout</code>은 셸 세션 종료의 의미로 같이 묶여 나온다.",
            "<code>cat</code>과 <code>more</code>의 차이는 출력 방식과 파일 크기 적합성이다."
          ],
          "checklist": [
            "OS, kernel, shell의 관계를 2문장 안에 설명할 수 있다.",
            "로그인 이후 프롬프트가 뜨는 이유를 설명할 수 있다.",
            "<code>who</code>, <code>last</code>, <code>which</code>, <code>uname</code>의 역할을 구분할 수 있다."
          ],
          "quiz": [
            {
              "q": "왜 shell을 command interpreter라고 부르는가?",
              "a": "사용자가 입력한 문자열 명령을 읽고 해석해서 kernel이 이해할 수 있는 요청 흐름으로 연결하기 때문이다."
            },
            {
              "q": "<code>cat</code> 대신 <code>more</code>를 써야 하는 상황은?",
              "a": "파일이 길어서 화면 단위로 확인해야 할 때다. <code>cat</code>은 전체를 한 번에 뿌려 버리므로 긴 파일 확인에는 불편하다."
            },
            {
              "q": "<code>which</code>와 <code>man</code>의 차이는?",
              "a": "<code>which</code>는 명령 실행 파일의 위치를 찾고, <code>man</code>은 그 명령의 매뉴얼을 보여 준다."
            }
          ],
          "pages": 33
        },
        {
          "order": 2,
          "status": "ready",
          "id": "lec3",
          "badge": "Lec 3",
          "type": "core",
          "title": "VIM 입문과 모드 사고방식",
          "source": "lec3-4471013 editor I.pdf",
          "theme": "VIM / .bashrc / 저장 / 이동",
          "summary": "VIM을 왜 배우는지, VIM의 입력 모드와 명령 모드가 어떻게 다르며, 편집 버퍼와 디스크 파일 관계가 어떻게 되는지 이해시키는 강의다.",
          "narrative": [
            "이 강의는 VIM을 단축키 모음으로 외우기 전에 '왜 이런 편집기가 존재하는가'를 먼저 설명한다. Linux 환경에서는 설정 파일, 코드, 스크립트, 매뉴얼 조각을 빠르게 수정해야 하므로 CLI 기반 편집기가 중요하다. 그래서 <code>cat</code>이나 <code>more</code>로는 부족한 스크롤, 검색, 치환 기능을 VIM이 맡는다.",
            "가장 중요한 개념은 모드다. VIM은 시작하자마자 command mode에 있고, 이때 키 입력은 텍스트가 아니라 명령으로 해석된다. 문자를 실제로 입력하려면 input mode로 들어가야 한다. 이 한 문장만 정확히 이해해도 '왜 VIM이 어렵게 느껴지는지'가 풀린다.",
            "또한 강의는 편집 버퍼와 디스크 파일을 분리해 설명한다. 화면에서 편집한 내용은 메모리의 editing buffer에 반영될 뿐이고, <code>:w</code> 같은 저장 명령을 실행해야 디스크 파일에 기록된다. 즉 편집과 저장은 다른 단계다."
          ],
          "concepts": [
            {
              "title": ".bashrc의 의미",
              "body": "<code>.bashrc</code>는 로그인 시 읽히는 bash 시작 파일이다. 숨김 파일이며, 자주 쓰는 alias나 환경 설정을 넣어 두면 로그인할 때 자동으로 적용된다. 즉 '쉘 행동을 미리 정의하는 파일'이다."
            },
            {
              "title": "VIM의 장점",
              "body": "기본 편집기, 적은 자원 사용, 강력한 단축키, 플러그인, 설정 파일 <code>.vimrc</code> 지원이 포인트다. 마우스 없이도 빠르고 결정적인 편집이 가능하다는 점이 핵심 장점이다."
            },
            {
              "title": "Command mode vs Input mode",
              "body": "Command mode는 제어 모드이고 Input mode는 실제 텍스트 입력 모드다. 시험에서는 'VIM 시작 기본 모드는 command mode'라는 말을 반드시 붙여 주는 것이 좋다."
            },
            {
              "title": "편집 버퍼와 저장",
              "body": "버퍼는 메모리 상의 작업 공간이다. 여기에 쓴 내용이 자동으로 파일로 내려가지 않는다. <code>:w</code>는 저장, <code>:q</code>는 종료, <code>:wq</code>는 저장 후 종료다."
            }
          ],
          "commands": [
            {
              "name": "VIM 시작과 종료",
              "syntax": "vim [file]\n:w\n:q\n:q!\n:wq\nZZ",
              "idea": "파일을 열고, 저장하고, 종료하는 가장 기본 동작이다.",
              "example": "vim notes.txt\n:wq",
              "pitfall": "<code>:q</code>는 변경 사항이 남아 있으면 종료가 막힐 수 있고, 강제 종료는 <code>:q!</code>다."
            },
            {
              "name": "입력 모드 진입",
              "syntax": "i\na\no\nO",
              "idea": "문자를 실제로 입력하려면 input mode로 들어가야 한다.",
              "example": "iHello<Esc>\noNew line<Esc>",
              "pitfall": "<code>i</code>와 <code>a</code>의 차이는 커서 앞/뒤, <code>o</code>와 <code>O</code>는 아래/위 새 줄이다."
            },
            {
              "name": "커서 이동",
              "syntax": "h j k l\n0 ^ $\nw b\ngg G\n:n",
              "idea": "문자, 줄, 단어, 파일 범위를 가로질러 이동하는 명령군이다.",
              "example": "gg\n42G\n$",
              "pitfall": "<code>0</code>은 줄 맨 앞, <code>^</code>는 공백 제외 첫 문자다."
            },
            {
              "name": "스크롤과 줄 번호",
              "syntax": "Ctrl+F\nCtrl+B\nCtrl+D\nCtrl+U\n:set number",
              "idea": "화면 단위 탐색과 현재 위치 파악에 쓰인다.",
              "example": ":set number\nCtrl+D",
              "pitfall": "스크롤은 커서 이동과 다르다. 큰 파일에서 화면 단위로 빠르게 훑을 때 특히 중요하다."
            }
          ],
          "pitfalls": [
            "기본 모드가 입력 모드라고 착각하면 VIM이 계속 오작동처럼 느껴진다.",
            "<code>:w</code>는 저장이지 종료가 아니다. <code>:q</code>와 역할을 구분해야 한다.",
            "버퍼와 디스크 파일을 구분하지 못하면 '왜 저장 안 했는데 화면에 보이지?' 같은 혼란이 생긴다."
          ],
          "checklist": [
            "<code>.bashrc</code>와 <code>.vimrc</code>의 역할 차이를 설명할 수 있다.",
            "VIM의 두 모드를 말로 구분할 수 있다.",
            "<code>gg</code>, <code>G</code>, <code>:n</code>의 용도를 구분할 수 있다."
          ],
          "quiz": [
            {
              "q": "VIM에서 파일을 열고 수정한 뒤 저장하지 않으면 내용은 어디에 남아 있는가?",
              "a": "editing buffer에만 반영되어 있고 디스크 파일에는 아직 기록되지 않는다."
            },
            {
              "q": "<code>0</code>과 <code>^</code>의 차이는?",
              "a": "<code>0</code>은 줄의 완전한 맨 앞, <code>^</code>는 앞 공백을 건너뛴 첫 문자로 이동한다."
            },
            {
              "q": "<code>ZZ</code>는 어떤 계열의 명령인가?",
              "a": "저장 후 종료 계열이다. 실전에서 <code>:wq</code>와 같은 맥락으로 외우면 된다."
            }
          ],
          "pages": 22
        },
        {
          "order": 3,
          "status": "ready",
          "id": "lec4",
          "badge": "Lec 4",
          "type": "core",
          "title": "VIM 편집 조작, 삭제, 복사, 붙여넣기",
          "source": "lec4-4471013-editor II.pdf",
          "theme": "입력 전환 / 수정 / 버퍼 활용",
          "summary": "VIM에서 내용을 바꾸는 실제 손동작을 다룬다. 삽입, 변경, 삭제, 붙여넣기, 복사, 선택을 묶어서 '편집 버퍼를 다루는 법'으로 이해해야 한다.",
          "narrative": [
            "이 강의는 VIM을 진짜 편집기에 가깝게 만들어 준다. 단순 이동이 아니라 텍스트를 효율적으로 고치는 동작을 배우기 때문이다. 특히 <code>r</code>, <code>R</code>, <code>s</code>, <code>C</code>, <code>cc</code>, <code>cw</code>처럼 '무엇을 지우고 어떤 모드로 들어가는지'가 명령마다 다르다.",
            "삭제와 복사, 붙여넣기는 모두 임시 버퍼를 공유한다는 점이 중요하다. <code>dd</code>로 줄을 지우면 사라지는 동시에 버퍼에 저장되고, 이어서 <code>p</code>나 <code>P</code>로 다시 넣을 수 있다. 그래서 이 강의의 진짜 핵심은 '편집 버퍼를 이용한 재사용'이다.",
            "시험에서는 각 명령의 미세한 차이를 묻기 쉽다. 예를 들어 <code>p</code>와 <code>P</code>, <code>x</code>와 <code>X</code>, <code>cw</code>와 <code>cc</code>를 비교하면 된다. 비교형으로 공부해야 오래 간다."
          ],
          "concepts": [
            {
              "title": "삽입 시작 위치 차이",
              "body": "<code>i</code>/<code>I</code>/<code>a</code>/<code>A</code>/<code>o</code>/<code>O</code>는 모두 input mode로 들어가지만 시작 위치가 다르다. 이 차이를 이해하면 줄 전체를 다시 쓰는 작업이 빨라진다."
            },
            {
              "title": "change 계열 명령",
              "body": "<code>cw</code>는 현재 단어를 바꾸고, <code>cc</code>는 현재 줄 전체를 바꾸며, <code>C</code>는 현재 커서부터 줄 끝까지 바꾼다. 즉 범위가 다르다."
            },
            {
              "title": "undo와 반복",
              "body": "<code>u</code>는 직전 작업 취소, <code>.</code>는 직전 편집 동작 반복이다. 특히 <code>.</code>는 동일한 수정을 여러 위치에 빠르게 재적용할 때 매우 강력하다."
            },
            {
              "title": "visual selection",
              "body": "<code>v</code>는 일반 시각 선택, <code>Ctrl+v</code>는 블록 선택이다. 선택 후 삭제, 복사, 수정, 붙여넣기 같은 다른 동작과 결합할 수 있다."
            }
          ],
          "commands": [
            {
              "name": "change 계열",
              "syntax": "r\nR\ns\nC\ncc\ncw",
              "idea": "문자 하나만 덮어쓸지, 현재 단어를 바꿀지, 현재 줄을 갈아엎을지를 고르는 명령군이다.",
              "example": "cwnew_word<Esc>\nccrewritten line<Esc>",
              "pitfall": "<code>r</code>만 command mode에 남고, 나머지 다수는 input mode로 넘어간다는 차이를 기억해야 한다."
            },
            {
              "name": "undo / repeat",
              "syntax": "u\n.",
              "idea": "한 번 취소하고, 한 번 더 같은 편집을 반복한다.",
              "example": "cwlinux<Esc>\n.\n.",
              "pitfall": "<code>.</code>는 마지막 '편집 행동'을 반복하는 것이지 마지막 키 하나를 반복하는 것이 아니다."
            },
            {
              "name": "삭제와 붙여넣기",
              "syntax": "x\nX\nD\ndd\np\nP",
              "idea": "삭제된 내용은 임시 버퍼에 남아 다시 붙일 수 있다.",
              "example": "dd\nP",
              "pitfall": "<code>p</code>는 뒤, <code>P</code>는 앞에 붙인다. 줄 단위와 문자 단위 동작이 섞이면 위치 감각이 흔들리기 쉽다."
            },
            {
              "name": "복사와 선택",
              "syntax": "yy\n3Y\n:5,8 y\nv\nCtrl+v\n~",
              "idea": "현재 줄, 여러 줄, 범위 줄 복사와 시각 선택을 다룬다.",
              "example": "yy\np\n:5,8 y\nP",
              "pitfall": "복사도 삭제처럼 버퍼를 사용한다. 그래서 복사 후 붙여넣기 흐름을 같이 외워야 한다."
            }
          ],
          "pitfalls": [
            "<code>dd</code>는 단순 삭제가 아니라 줄을 잘라 버퍼에 넣는 동작으로 이해해야 한다.",
            "<code>C</code>, <code>cc</code>, <code>cw</code>는 모두 change 계열이지만 삭제 범위가 다르다.",
            "선택 모드에서도 결국 다른 명령과 결합한다는 점을 놓치면 활용을 못 한다."
          ],
          "checklist": [
            "<code>p</code>와 <code>P</code>의 방향 차이를 설명할 수 있다.",
            "<code>cw</code>, <code>cc</code>, <code>C</code>의 범위를 비교할 수 있다.",
            "삭제된 내용이 임시 버퍼에 남는다는 사실을 말할 수 있다."
          ],
          "quiz": [
            {
              "q": "<code>dd</code> 한 뒤 <code>P</code>를 누르면 무슨 일이 벌어지는가?",
              "a": "지운 현재 줄이 임시 버퍼에 남아 있으므로, 현재 위치 앞쪽에 다시 붙는다."
            },
            {
              "q": "<code>cw</code>와 <code>cc</code>의 차이는?",
              "a": "<code>cw</code>는 현재 단어를 바꾸고, <code>cc</code>는 현재 줄 전체를 바꾼다."
            },
            {
              "q": "<code>.</code> 명령은 왜 생산성이 높은가?",
              "a": "방금 수행한 편집 패턴을 그대로 반복해 주기 때문에 같은 수정 작업을 여러 위치에서 빠르게 재현할 수 있다."
            }
          ],
          "pages": 25
        },
        {
          "order": 4,
          "status": "ready",
          "id": "lab4",
          "badge": "Lab 4",
          "type": "practice",
          "title": "VIM 실습 루틴",
          "source": "lec4-practice-4471013-vim.pdf",
          "theme": "손 연습 / 편집 체화",
          "summary": "VIM 명령을 눈으로 아는 수준에서 손으로 바로 나가게 만드는 실습 자료다. 설치, 파일 작성, 줄 삭제, 문단 수정 같은 동작이 중심이다.",
          "narrative": [
            "실습 PDF는 새로운 이론보다 '지금까지 배운 것을 몸에 붙이는 단계'라고 보면 된다. 특히 실제 파일을 만들고 내용을 고치는 과정에서 command mode와 input mode를 자연스럽게 오가게 만든다.",
            "슬라이드에 나온 과제는 크게 세 가지 감각을 점검한다. 첫째, VIM을 열고 종료할 수 있는가. 둘째, 주어진 텍스트를 정확히 입력하고 수정할 수 있는가. 셋째, 줄/문단 삭제나 치환 같은 편집 연산을 범위 의식과 함께 실행할 수 있는가.",
            "시험 직전에는 이 실습 PDF를 기준으로 '빈 파일에서 시작해서 편집을 완수하는 흐름'을 리허설하면 좋다. 명령의 의미를 안다고 해도 손이 멈추면 실습형 문제에서 시간을 잃기 때문이다."
          ],
          "concepts": [
            {
              "title": "설치 확인",
              "body": "슬라이드는 Ubuntu 환경에서 VIM 설치를 먼저 확인하게 한다. 실제 시험 준비에서는 <code>vim --version</code>으로 존재 여부를 확인하는 습관이 좋다."
            },
            {
              "title": "새 파일 작성",
              "body": "빈 파일을 열고 내용을 정확히 입력하는 과정에서 <code>vim file</code>, 입력 모드 진입, 저장, 종료가 반복된다. 가장 기본적이지만 가장 많이 쓰는 흐름이다."
            },
            {
              "title": "범위 삭제",
              "body": "특정 문단이나 줄 범위를 삭제하는 요구가 나온다. 여기서 핵심은 현재 커서 위치를 의식하면서 <code>dd</code>, 줄 번호 이동, 선택을 조합하는 것이다."
            },
            {
              "title": "요약본 병행",
              "body": "마지막 실습은 별도의 VIM summary 자료를 보라고 한다. 즉 수업도 '전체 동작을 압축 정리해 다시 보라'는 구조로 설계되어 있다."
            }
          ],
          "commands": [
            {
              "name": "실습 시작 세트",
              "syntax": "vim prac1.txt\ni ... Esc\n:wq",
              "idea": "새 파일 열기, 입력, 저장 종료를 한 번에 반복한다.",
              "example": "vim prac1.txt\niFirst line<Esc>\n:wq",
              "pitfall": "입력 후 바로 종료하지 말고 저장을 먼저 해야 한다."
            },
            {
              "name": "줄 단위 수정",
              "syntax": "dd\nP\ncw\ncc",
              "idea": "줄 삭제, 되돌리기, 단어/줄 수정으로 실습 과제를 해결한다.",
              "example": "5G\ndd\nP",
              "pitfall": "삭제와 복사를 따로 생각하지 말고 '버퍼에 넣고 다시 쓰는 흐름'으로 이해해야 빠르다."
            }
          ],
          "pitfalls": [
            "실습에서는 명령 하나보다 작업 순서가 더 중요하다. 열기 → 이동 → 수정 → 저장 순서를 고정하라.",
            "줄 번호 이동 없이 감으로만 편집하면 범위 문제에서 실수가 난다."
          ],
          "checklist": [
            "빈 파일 생성부터 저장 종료까지 10초 안에 할 수 있다.",
            "특정 줄로 이동해서 삭제하고 다시 붙이는 흐름을 손으로 재현할 수 있다."
          ],
          "quiz": [
            {
              "q": "실습 PDF가 왜 중요한가?",
              "a": "강의 개념을 실전 손동작으로 바꾸는 단계이기 때문이다. 시험형 실습 문제는 이해보다 반응 속도가 더 중요할 때가 많다."
            }
          ],
          "pages": 7
        },
        {
          "order": 5,
          "status": "ready",
          "id": "lec5",
          "badge": "Lec 5",
          "type": "core",
          "title": "VIM 고급 기능과 추가 Linux 명령",
          "source": "lec5-4471013-editor III and more commands.pdf",
          "theme": "설정 / 검색 / 치환 / 텍스트 처리",
          "summary": "VIM 설정과 분할 창, 검색과 치환, 그리고 쉘에서 자주 쓰는 텍스트 처리 명령을 함께 다루는 확장 강의다.",
          "narrative": [
            "강의 전반부는 VIM을 '조금 아는 수준'에서 '실제로 맞춤화해서 쓰는 수준'으로 끌어올린다. <code>:set</code>으로 탭 폭, 자동 들여쓰기, 줄 번호를 조정하고, <code>:shell</code>이나 <code>:!cmd</code>로 외부 명령을 부르는 구조를 보여 준다. 이는 VIM이 단순 에디터가 아니라 작업 허브라는 뜻이다.",
            "중반부의 검색과 치환은 시험에서 매우 중요하다. 단순 문자열 찾기가 아니라, 라인 시작/끝, 단어 경계, 문자 클래스, 치환 옵션까지 다루기 때문이다. 그래서 <code>/pattern</code>과 <code>:%s/old/new/g</code>를 별개가 아니라 '검색 기반 편집'으로 연결해서 이해해야 한다.",
            "후반부는 쉘 명령 확장 파트다. 시간, 달력, 계산, 로그인 사용자, 네트워크 상태, 파일 출력, 패턴 검색, 파일 찾기, 정렬, 카운트, 파일 분할, 디스크 사용량까지 이어진다. 즉 '정보 보기 → 가공하기 → 찾기 → 요약하기' 흐름으로 외우면 된다."
          ],
          "concepts": [
            {
              "title": "선택적 설정과 .vimrc",
              "body": "<code>:set ts=4</code>, <code>sts</code>, <code>sw</code>, <code>textwidth</code>, <code>smartindent</code>, <code>number</code>는 편집 환경을 바꾸는 명령이다. 이를 <code>~/.vimrc</code>에 넣으면 실행 시 자동 적용된다."
            },
            {
              "title": "분할 창과 외부 연동",
              "body": "<code>:vnew</code>, <code>:split</code>, <code>Ctrl+w</code> 계열로 창을 나누고 이동할 수 있다. <code>:shell</code>, <code>:!cmd</code>, <code>:source</code>는 VIM과 바깥 세계를 연결한다."
            },
            {
              "title": "검색 패턴",
              "body": "라인 시작 <code>^</code>, 라인 끝 <code>$</code>, 단어 경계 <code>\\&lt;</code>/<code>\\&gt;</code>, 문자 클래스, 논리합 <code>\\|</code>, 미리 정의된 클래스 <code>\\d</code>, <code>\\s</code>, <code>.</code>를 이해하면 검색 표현력이 확 올라간다."
            },
            {
              "title": "쉘 명령의 역할 묶음",
              "body": "<code>grep</code>은 파일 내용 검색, <code>find</code>는 파일/디렉터리 이름 검색, <code>sort</code>는 정렬, <code>wc</code>는 개수 세기, <code>split</code>은 파일 분할, <code>df</code>/<code>du</code>는 디스크 사용량 확인이다."
            }
          ],
          "commands": [
            {
              "name": "VIM 설정",
              "syntax": ":set ts=4\n:set sw=4\n:set smartindent\n:set number\n:set fileencoding=utf-8",
              "idea": "탭, 들여쓰기, 줄 번호, 인코딩처럼 편집 환경 자체를 제어한다.",
              "example": ":set number\n:set fileencoding=utf-8",
              "pitfall": "<code>encoding</code>과 <code>fileencoding</code>은 같은 말처럼 보이지만 표시 인코딩과 현재 파일 인코딩 맥락이 다를 수 있다."
            },
            {
              "name": "검색과 치환",
              "syntax": "/pattern\nn\nN\n:%s/pattern/string/g",
              "idea": "찾고, 다음 결과로 이동하고, 범위를 지정해 치환한다.",
              "example": "/You\n:%s/You/you/g",
              "pitfall": "<code>g</code> 옵션이 없으면 한 줄 안에서 첫 번째 일치만 바뀐다."
            },
            {
              "name": "grep / find / sort / wc",
              "syntax": "grep pattern files\nfind dir -name \"pattern\"\nsort [-n] [-r] file\nwc [-lwc] file",
              "idea": "내용 검색, 이름 검색, 정렬, 개수 세기를 담당하는 대표 텍스트 처리 도구다.",
              "example": "grep -n \"from\" file2\nfind . -name \"*.txt\"\nsort -n scores.txt\nwc -l main.c",
              "pitfall": "<code>grep</code>과 <code>find</code>의 검색 대상이 다르다. 하나는 파일 내용, 다른 하나는 파일 이름/경로다."
            },
            {
              "name": "date / cal / bc / users 계열",
              "syntax": "date [-u]\ncal [month] [year]\nbc\nusers\nwho\nw\nwhoami\nid",
              "idea": "시간, 달력, 계산, 사용자 식별과 로그인 상태를 보는 기본 명령 묶음이다.",
              "example": "date -u\ncal 3 2026\nbc -l\nwhoami\nid",
              "pitfall": "<code>users</code>, <code>who</code>, <code>w</code>, <code>whoami</code>는 모두 사용자 관련이지만 보여 주는 정보 깊이가 다르다."
            },
            {
              "name": "cat / split / df / du",
              "syntax": "cat file1 file2 > new\nsplit [-l n] in_file out_prefix\ndf\ndu -sh dir",
              "idea": "파일 합치기, 큰 파일 나누기, 파일 시스템/디렉터리 용량 확인에 쓴다.",
              "example": "cat a.txt b.txt > merged.txt\nsplit -l 1000 big.txt part_\ndu -sh .",
              "pitfall": "<code>df</code>는 파일 시스템 단위, <code>du</code>는 디렉터리/파일 사용량 단위라는 차이가 있다."
            }
          ],
          "pitfalls": [
            "<code>g</code> 옵션 없이 치환하면 한 줄에서 첫 매치만 바뀐다.",
            "<code>grep</code>은 '파일 내용'이고 <code>find</code>는 '파일 이름과 경로'다.",
            "<code>who</code>는 로그인 정보, <code>w</code>는 로그인 정보에 현재 작업까지 덧붙여 보여 준다.",
            "<code>sort</code> 기본은 문자열 정렬이며 숫자 정렬은 <code>-n</code>이 필요하다."
          ],
          "checklist": [
            "<code>.vimrc</code>에 설정을 넣는 이유를 설명할 수 있다.",
            "검색 패턴에서 <code>^</code>, <code>$</code>, <code>\\d</code>, <code>\\s</code> 의미를 말할 수 있다.",
            "<code>grep</code>, <code>find</code>, <code>sort</code>, <code>wc</code>를 문제 유형에 맞게 고를 수 있다."
          ],
          "quiz": [
            {
              "q": "<code>:%s/You/you/g</code>에서 <code>%</code>와 <code>g</code>는 각각 무엇을 뜻하는가?",
              "a": "<code>%</code>는 전체 줄 범위(1,$), <code>g</code>는 각 줄에서 모든 일치를 치환하라는 뜻이다."
            },
            {
              "q": "왜 <code>grep</code>과 <code>find</code>를 헷갈리면 안 되는가?",
              "a": "질문 대상이 다르기 때문이다. 내용 안의 패턴을 찾는지, 파일/디렉터리 이름 자체를 찾는지에 따라 써야 하는 명령이 갈린다."
            },
            {
              "q": "<code>du -sh</code>와 <code>df</code>의 차이는?",
              "a": "<code>du</code>는 특정 디렉터리나 파일이 실제로 쓰는 크기를 보고, <code>df</code>는 파일 시스템 전체의 남은 공간과 사용량을 본다."
            }
          ],
          "pages": 40
        },
        {
          "order": 6,
          "status": "ready",
          "id": "lab5",
          "badge": "Lab 5",
          "type": "practice",
          "title": "추가 명령어 실습",
          "source": "lec5-practice-4471013-more commands I.pdf",
          "theme": "옵션 확인 / 계산 / 치환 연습",
          "summary": "명령어 매뉴얼을 직접 보고, 날짜/시간/계산 명령을 써 보고, VIM 치환까지 연결하는 실습 자료다.",
          "narrative": [
            "이 실습은 '명령어를 어디까지 외워야 하나'에 대한 답을 준다. 전부 외우는 것이 아니라 <code>man</code>과 <code>--help</code>로 옵션을 읽을 수 있어야 한다는 점을 훈련시키기 때문이다.",
            "또한 <code>date -u</code> 같은 실제 옵션 사용, <code>bc</code> 계산, 파일 작성과 일괄 치환이 이어진다. 즉 읽고 끝내는 강의가 아니라, 짧은 명령 조합으로 문제를 해결하는 감각을 만드는 단계다.",
            "시험 대비용으로는 각 과제를 '어떤 명령 묶음을 불러오는가'로 정리하면 좋다. 옵션 확인 문제, 계산 문제, 텍스트 치환 문제, 파일 수정 문제로 나누면 된다."
          ],
          "concepts": [
            {
              "title": "매뉴얼 읽기 습관",
              "body": "처음 보는 명령이라도 <code>man</code>과 <code>--help</code>로 핵심 옵션을 찾아낼 수 있어야 한다. 실습은 이 능력을 직접 요구한다."
            },
            {
              "title": "UTC와 로컬 시간 구분",
              "body": "<code>date -u</code>는 UTC 기준 시간을 본다. 시험에서 로컬 시간과 표준 시간 개념을 묶어 물을 수 있다."
            },
            {
              "title": "bc는 쉘 안의 계산기",
              "body": "사칙연산뿐 아니라 수학 함수까지 쓸 수 있다. <code>bc -l</code>은 math library를 포함하는 확장 버전으로 이해하면 된다."
            },
            {
              "title": "일괄 치환의 감각",
              "body": "실습 마지막은 파일 속 숫자열을 통째로 바꾸게 한다. 이는 VIM 치환이 실무적으로 왜 강한지 보여 주는 예다."
            }
          ],
          "commands": [
            {
              "name": "옵션 확인 루틴",
              "syntax": "man command\ncommand --help",
              "idea": "모르는 명령의 기능과 옵션을 스스로 읽는 기본 루틴이다.",
              "example": "man date\ngrep --help",
              "pitfall": "명령만 암기하고 옵션을 읽지 못하면 응용 문제가 막힌다."
            },
            {
              "name": "계산과 치환",
              "syntax": "bc -l\n:%s/0123456789/9876543210/g",
              "idea": "계산 결과를 얻거나 특정 패턴을 일괄 수정할 때 쓴다.",
              "example": "bc -l\nsqrt(16)\nquit",
              "pitfall": "<code>bc</code>는 종료를 <code>quit</code>으로 하는 인터랙티브 도구라는 점도 같이 기억하라."
            }
          ],
          "pitfalls": [
            "옵션을 문제에서 바꿔 물으면 암기만 한 사람은 흔들린다. 직접 읽어 본 사람이 유리하다.",
            "치환 실습은 패턴과 문자열을 헷갈리지 않는지 보는 문제로 자주 바뀐다."
          ],
          "checklist": [
            "모르는 명령이 나와도 <code>man</code>으로 핵심 옵션을 찾을 수 있다.",
            "<code>bc</code>에 식을 넣고 결과를 해석할 수 있다."
          ],
          "quiz": [
            {
              "q": "실습에서 <code>man</code>을 강조하는 이유는?",
              "a": "모든 옵션을 외우기보다 스스로 읽고 적용하는 능력이 실제 Linux 사용 능력에 더 가깝기 때문이다."
            }
          ],
          "pages": 7
        },
        {
          "order": 7,
          "status": "ready",
          "id": "lec6",
          "badge": "Lec 6",
          "type": "core",
          "title": "파일, 디렉터리, 권한, 파이프라인",
          "source": "lec6-4471013-file and dir.pdf",
          "theme": "경로 / 권한 / 셸 입출력",
          "summary": "Linux 파일 시스템을 이해하는 데 필요한 거의 모든 기초를 담은 강의다. 파일 종류, 디렉터리 계층, 복사와 삭제, 권한, 메타문자, 리다이렉션, 파이프, history까지 이어진다.",
          "narrative": [
            "이 강의는 Linux를 '파일로 모든 것을 다루는 시스템'으로 이해하게 만든다. 일반 파일뿐 아니라 디렉터리, 장치 파일, 표준 입력과 출력도 파일처럼 취급된다는 관점이 처음에는 낯설지만, 뒤의 리다이렉션과 파이프를 이해하려면 꼭 필요하다.",
            "중간부는 경로와 파일 조작의 감각을 잡는다. <code>cd</code>와 <code>pwd</code>로 현재 위치를 알고, 상대 경로와 절대 경로를 구분하고, <code>mkdir</code>, <code>mv</code>, <code>cp</code>, <code>rm</code>, <code>ls</code>로 구조를 바꾼다. 여기서는 '무엇을 어디로 옮기고 지우는가'가 항상 질문의 핵심이다.",
            "후반부는 시험에서 가장 자주 틀리는 권한과 셸 입출력이다. <code>rwx</code>가 owner/group/others에 어떻게 배분되는지, <code>755</code>나 <code>644</code>를 어떻게 읽는지, 그리고 <code>&gt;</code>, <code>&gt;&gt;</code>, <code>|</code>, <code>tee</code>, <code>history</code>가 어떤 데이터 흐름을 만들지 정확히 말할 수 있어야 한다."
          ],
          "concepts": [
            {
              "title": "파일의 넓은 의미",
              "body": "Linux에서 파일은 단순 문서가 아니라 읽고 쓸 수 있는 추상 자원이다. 일반 파일, 디렉터리, 장치 파일뿐 아니라 표준 입력/출력도 파일처럼 다룬다."
            },
            {
              "title": "텍스트 파일 vs 바이너리 파일",
              "body": "텍스트 파일은 사람이 읽을 수 있는 문자 기반, 바이너리 파일은 프로그램이 해석해야 의미가 있는 이진 데이터다. 실행 파일은 대표적인 바이너리 파일 예다."
            },
            {
              "title": "디렉터리 계층과 경로",
              "body": "디렉터리는 다른 파일과 디렉터리를 조직하는 파일이다. 상대 경로는 현재 위치 기준, 절대 경로는 루트부터의 전체 경로다. <code>.</code>, <code>..</code>, <code>~</code> 의미를 정확히 알아야 한다."
            },
            {
              "title": "권한 구조",
              "body": "권한은 읽기(<code>r</code>), 쓰기(<code>w</code>), 실행(<code>x</code>)의 세 종류이고, owner/group/others 세 사용자 그룹에 따로 부여된다. 숫자 모드는 이 조합을 8진수 세 자리로 표현한다."
            }
          ],
          "commands": [
            {
              "name": "경로와 디렉터리 조작",
              "syntax": "cd [dir]\npwd\nmkdir dir\nrmdir dir\nmv src dst",
              "idea": "현재 위치 파악, 디렉터리 생성/삭제, 파일과 디렉터리 이동 및 이름 변경을 담당한다.",
              "example": "pwd\nmkdir ../../course/linux\nmv oldname newname",
              "pitfall": "<code>mv</code>는 이동뿐 아니라 이름 변경도 한다. <code>rmdir</code>는 비어 있는 디렉터리만 지운다."
            },
            {
              "name": "목록과 내용 확인",
              "syntax": "ls [-lartR]\ncat file\nmore file\nhead -n n file\ntail -n n file\nfile target",
              "idea": "무엇이 있는지, 안에 무엇이 있는지, 어떤 종류의 파일인지 확인한다.",
              "example": "ls -la\nhead -n 20 report.txt\nfile a.out",
              "pitfall": "<code>ls -a</code>는 숨김 파일 포함, <code>ls -R</code>은 재귀 목록이다. 옵션 의미가 서로 다르다."
            },
            {
              "name": "복사와 삭제",
              "syntax": "cp file1 file2\ncp -i files dir\ncp -r dir1 dir2\nrm file\nrm -i file\nrm -r dir",
              "idea": "파일과 디렉터리를 복사하거나 삭제한다.",
              "example": "cp -i notes.txt backup.txt\ncp -r src backup_src\nrm -r old_dir",
              "pitfall": "<code>rm -rf /</code>, <code>rm -rf *</code>, <code>rm -rf .</code> 같은 위험 조합은 강의에서 직접 경고한다."
            },
            {
              "name": "권한과 chmod",
              "syntax": "ls -l\nchmod 755 file\nchmod u+x script.sh\nchmod g-x report.txt",
              "idea": "현재 권한을 읽고 숫자 모드나 기호 모드로 수정한다.",
              "example": "chmod 644 notes.txt\nchmod u+x run.sh",
              "pitfall": "<code>755</code>는 소유자에게 <code>rwx</code>, 그룹과 기타 사용자에게 <code>r-x</code>다. 숫자와 문자 변환을 바로 해야 한다."
            },
            {
              "name": "메타 문자와 파이프",
              "syntax": "*  ?  [ ]\n>  >>  <\n$(cmd)\n|\ntee [-a] file\nhistory [n]",
              "idea": "와일드카드, 리다이렉션, 명령 치환, 파이프, 히스토리를 다룬다.",
              "example": "ls test*\nsort < unsorted | tee sorted\nhistory 10",
              "pitfall": "<code>&gt;</code>는 파일로 보내고, <code>|</code>는 다음 프로그램으로 보낸다. 목적지가 다르다."
            }
          ],
          "pitfalls": [
            "<code>rm -f directory</code>만으로는 일반 디렉터리 삭제가 되지 않는다. 디렉터리 재귀 삭제는 보통 <code>-r</code>가 핵심이다.",
            "실행 권한 <code>x</code>는 파일이면 실행 가능, 디렉터리면 그 안을 통과/열람 가능과 연결된다.",
            "<code>grep</code>은 파일 내용에 쓰고, 와일드카드 <code>*</code>는 셸이 먼저 파일 이름 확장에 쓴다는 점을 구분하라.",
            "<code>tee</code>는 stdout도 유지하면서 파일에도 저장하는 특수한 파이프 도구다."
          ],
          "checklist": [
            "상대 경로와 절대 경로를 예시로 설명할 수 있다.",
            "<code>755</code>, <code>644</code>, <code>400</code>을 문자 권한으로 바꿀 수 있다.",
            "<code>&gt;</code>, <code>&gt;&gt;</code>, <code>|</code>, <code>tee</code>의 데이터 흐름 차이를 설명할 수 있다."
          ],
          "quiz": [
            {
              "q": "<code>rmdir</code>와 <code>rm -r</code>의 차이는?",
              "a": "<code>rmdir</code>는 비어 있는 디렉터리만 삭제하고, <code>rm -r</code>는 하위 내용까지 재귀적으로 삭제할 수 있다."
            },
            {
              "q": "왜 디렉터리도 파일이라고 설명하는가?",
              "a": "다른 파일과 디렉터리에 접근하기 위한 정보를 저장하는 특수한 파일이기 때문이다."
            },
            {
              "q": "<code>sort &lt; unsorted | tee sorted</code>와 <code>sort &lt; unsorted &gt; sorted</code>의 차이는?",
              "a": "둘 다 정렬 결과를 파일로 남길 수 있지만, <code>tee</code>를 쓰면 결과가 화면(stdout)에도 유지되고 동시에 파일에도 저장된다."
            }
          ],
          "pages": 45
        }
      ]
    },
    {
      "id": "multicultural-understanding",
      "meta": {
        "title": "다문화사회의 이해 시험 강의 노트",
        "summary": "Desktop/다문화사회의이해 폴더의 주차별 강의 PDF를 바탕으로, 문화 개념의 기초부터 세계화, 언어와 권력, 글로벌 경제까지 시험 대비용으로 다시 강의하듯 엮은 학습 사이트다. 핵심은 용어 정의를 외우는 데서 멈추지 않고, 개념 비교와 사례 해석, 서술형 답안 틀까지 한 번에 잡는 것이다.",
        "courseLabel": "다문화사회의 이해",
        "quickGuideLabel": "Core Frames",
        "quickGuideTitle": "개념을 바로 세우는 핵심 프레임",
        "atlasLabel": "Issue Atlas",
        "atlasTitle": "쟁점 아틀라스",
        "atlasFilterPlaceholder": "예: 문화상대주의, 세계화, 신자유주의",
        "drillLabel": "Essay Drills",
        "drillTitle": "서술형 대비 루틴",
        "lectureDetailMiniLabel": "Key Cards",
        "lectureDetailTitle": "시험용 핵심 카드",
        "lectureSyntaxLabel": "답안 틀",
        "lectureExampleLabel": "예시/사례",
        "lectureDetailEmpty": "아직 이 강의의 시험용 핵심 카드가 작성되지 않았습니다.",
        "statsLectureCards": "핵심 카드",
        "statsAtlasItems": "쟁점 묶음",
        "courseId": "multicultural-understanding",
        "sources": [
          {
            "file": "[2주차] 문화란 무엇인가.pdf",
            "pages": 29
          },
          {
            "file": "[3주차] 세계화와 문화.pdf",
            "pages": 27
          },
          {
            "file": "[4주차] 언어와 소통.pdf",
            "pages": 29
          },
          {
            "file": "[5주차] 글로벌 경제.pdf",
            "pages": 26
          },
          {
            "file": "문화상대주의_낯선곳에서 나를 만나다.pdf",
            "pages": 19
          }
        ],
        "generatedAt": "2026-03-31T05:25:49.875689+00:00",
        "authoredLectureCount": 5,
        "draftLectureCount": 0
      },
      "fastRecall": [
        "문화는 타고나는 것이 아니라 학습되고 공유되며 변화하는 삶의 방식이다.",
        "문화상대주의는 '무조건 다 허용'이 아니라, 먼저 맥락 속에서 이해하자는 분석 태도다.",
        "오늘날 세계화의 핵심 역동은 시공간 압축, 유연한 축적, 증가하는 이주, 불균등한 발전이다.",
        "언어는 말만이 아니라 제스처, 침묵, 신체언어, 디지털 플랫폼까지 포함하는 소통 체계다.",
        "근대화 이론은 같은 발전 경로를 가정하고, 종속 이론은 불평등한 세계경제 구조를 문제 삼는다.",
        "상품 사슬과 마찰 개념은 소비자와 생산자가 어떻게 불평등하게 연결되는지 보여 준다."
      ],
      "examMap": [
        {
          "title": "이 과목의 중심은 '차이를 어떻게 이해할 것인가'다",
          "body": "단순히 외국 문화를 소개하는 과목이 아니라, 익숙한 것을 낯설게 보고 타인의 실천을 맥락 속에서 읽는 방법을 배우는 과목이다. 그래서 개념 정의보다 비교와 해석 능력이 더 중요하다."
        },
        {
          "title": "2주차 개념이 나머지 주차의 언어가 된다",
          "body": "규범, 가치, 상징, 마음의 지도, 문화상대주의, 권력, 헤게모니, 행위성을 2주차에서 잡아야 3주차 이후 사례를 읽을 수 있다. 이후 주차는 모두 이 렌즈를 확장해서 쓰는 방식이다."
        },
        {
          "title": "세계화는 '연결'만이 아니라 '불평등한 연결'이다",
          "body": "사람, 상품, 정보가 더 빨리 움직인다고 해서 모두가 같은 이익을 얻는 것은 아니다. 이 과목은 연결과 동시에 발생하는 불균등한 발전, 종속, 마찰을 계속 추적한다."
        },
        {
          "title": "언어 파트는 소통을 권력 문제로 읽는 훈련이다",
          "body": "언어를 단순 전달 수단이 아니라 계급, 젠더, 지위, 디지털 격차와 연결해서 본다. 따라서 '누가 말할 수 있는가', '누구의 말이 위신을 갖는가'가 핵심 질문이다."
        },
        {
          "title": "글로벌 경제 파트는 이론 비교와 사례 연결이 핵심이다",
          "body": "근대화 이론, 종속 이론, 세계체계 이론, 신자유주의를 구분하고, 카카오·참치·팜유·이주노동 사례에 적용할 수 있어야 한다. 암기보다 '이 사례를 어떤 틀로 읽을 것인가'가 중요하다."
        },
        {
          "title": "시험은 서술형에 강한 구조다",
          "body": "정의만 적으면 점수가 약하고, 개념 비교와 사례 적용을 붙여야 답안이 탄탄해진다. '정의 → 비교 → 사례 → 함의' 순서를 습관화하면 대부분의 문항에 대응할 수 있다."
        }
      ],
      "cramPlan": [
        {
          "time": "0-15분",
          "title": "문화 개념과 비교 틀 정리",
          "body": "<code>문화</code>, <code>규범/가치/상징</code>, <code>자문화중심주의</code>, <code>문화상대주의</code>, <code>권력/헤게모니/행위성</code>을 먼저 고정한다."
        },
        {
          "time": "15-30분",
          "title": "세계화 파트 구조화",
          "body": "<code>시공간 압축</code>, <code>유연한 축적</code>, <code>이주</code>, <code>불균등한 발전</code>과 <code>동질화/혼합/세계시민주의</code>를 사례와 함께 묶어 외운다."
        },
        {
          "time": "30-45분",
          "title": "언어와 권력 파트 복습",
          "body": "<code>생산성/전위</code>, <code>침묵과 권력</code>, <code>사피어-워프 vs 사회언어학</code>, <code>문화 자본</code>, <code>디지털 행동주의</code>를 비교형으로 정리한다."
        },
        {
          "time": "45-60분",
          "title": "글로벌 경제 이론과 사례 매칭",
          "body": "<code>근대화</code>, <code>종속</code>, <code>세계체계</code>, <code>신자유주의</code>, <code>상품 사슬/마찰</code>을 카카오, 참치, 팜유, 이주노동 사례와 연결한다."
        }
      ],
      "vimCheat": [
        {
          "title": "문화 기본 프레임",
          "bullets": [
            "문화는 유전이 아니라 <code>문화화(enculturation)</code>를 통해 배운다.",
            "문화는 공유되지만 고정되지 않고, 협상되고 변화한다.",
            "<code>규범</code>, <code>가치</code>, <code>상징</code>, <code>마음의 지도</code>를 묶어서 써야 답이 입체적이다.",
            "<code>권력</code>은 문화 밖에 있는 것이 아니라 문화 속 규범과 제도에 스며 있다."
          ]
        },
        {
          "title": "세계화 읽기 틀",
          "bullets": [
            "오늘날 세계화는 <code>시공간 압축</code>, <code>유연한 축적</code>, <code>이주 증가</code>, <code>불균등한 발전</code>으로 설명한다.",
            "세계화의 결과는 단순 동질화가 아니라 혼합, 협상, 재구성으로 나타난다.",
            "다문화가족은 세계화의 추상 개념이 생활세계에서 만나는 <code>문화교차지역</code>의 예다.",
            "커피, 초콜릿, 스마트폰처럼 익숙한 사물을 따라가면 세계적 연결이 보인다."
          ]
        },
        {
          "title": "언어와 권력 읽기 틀",
          "bullets": [
            "언어는 말뿐 아니라 제스처, 침묵, 신체언어, 디지털 기호까지 포함한다.",
            "침묵은 결핍이 아니라 지위, 예절, 권력의 표현일 수 있다.",
            "<code>사피어-워프</code>는 언어가 사고를 형성한다고 보고, <code>사회언어학</code>은 사회적 맥락이 언어를 만든다고 본다.",
            "<code>문화 자본</code>과 <code>위신 언어</code>는 왜 특정 말하기 방식이 더 인정받는지 설명한다."
          ]
        },
        {
          "title": "글로벌 경제 읽기 틀",
          "bullets": [
            "<code>근대화 이론</code>은 같은 발전 경로를 가정한다.",
            "<code>종속 이론</code>은 식민주의 이후에도 지속되는 불평등 구조를 본다.",
            "<code>세계체계 이론</code>은 중심부·준주변부·주변부 위치를 본다.",
            "<code>상품 사슬</code>과 <code>마찰</code>은 생산자와 소비자의 연결이 왜 불안정하고 불평등한지 보여 준다."
          ]
        }
      ],
      "commandAtlas": [
        {
          "title": "문화 개념",
          "items": [
            {
              "name": "문화",
              "use": "삶의 방식 전체를 가리키는 넓은 개념이다. 학습되고, 공유되며, 변화하고, 상징적이면서 물질적이다.",
              "compare": "전통 유산이나 예술만을 뜻하는 좁은 의미로 이해하면 안 된다.",
              "example": "벌 유충과 양파 수프 사례는 무엇이 음식인지조차 문화마다 다를 수 있음을 보여 준다."
            },
            {
              "name": "규범 / 가치 / 상징 / 마음의 지도",
              "use": "문화를 구성하는 핵심 요소 묶음이다. 사람들의 행동과 판단, 의미 부여 방식을 설명할 때 함께 사용한다.",
              "compare": "규범은 '어떻게 해야 하는가', 가치는 '무엇이 중요하다고 여겨지는가', 상징은 '무엇이 무엇을 대표하는가'에 가깝다.",
              "example": "혼인 규범, 자유나 평등 같은 가치, 히잡이나 종교적 상징, 인간 분류 방식이 모두 이 틀로 읽힌다."
            },
            {
              "name": "자문화중심주의 / 문화상대주의",
              "use": "타인의 문화를 해석할 때 가장 기본이 되는 비교 틀이다.",
              "compare": "자문화중심주의는 자기 기준으로 판단하고, 문화상대주의는 먼저 맥락 속 의미를 이해하려 한다.",
              "example": "히잡을 무조건 억압의 상징으로만 보는 태도는 자문화중심주의적 해석이 될 수 있다."
            },
            {
              "name": "권력 / 헤게모니 / 행위성",
              "use": "문화 속 질서가 어떻게 유지되고 또 어떻게 도전받는지 설명한다.",
              "compare": "헤게모니는 강압보다 동의와 내면화를 통한 지배, 행위성은 그 질서에 균열을 내는 능력이다.",
              "example": "학교가 복장 규범을 집행하는 동시에 논쟁의 장이 되는 사례가 여기에 해당한다."
            }
          ]
        },
        {
          "title": "세계화와 문화",
          "items": [
            {
              "name": "시공간 압축 / 유연한 축적",
              "use": "오늘날 세계화의 경제·기술적 핵심 역동을 설명한다.",
              "compare": "시공간 압축은 거리와 시간 감각의 변화, 유연한 축적은 이윤 극대화를 위한 생산 이동 전략에 가깝다.",
              "example": "항공·인터넷·스마트폰은 시공간 압축, 해외 공장 이전과 오프쇼어링은 유연한 축적이다."
            },
            {
              "name": "이주 / 불균등한 발전",
              "use": "사람의 이동과 혜택의 불균형을 함께 읽는다.",
              "compare": "연결이 확대된다고 해서 혜택이 고르게 분배되는 것은 아니라는 점이 핵심이다.",
              "example": "국제결혼 가족, 송금, 디지털 접근성 격차, 국가별 인터넷 이용률 차이가 여기에 해당한다."
            },
            {
              "name": "동질화 / 혼합 / 세계시민주의",
              "use": "세계화가 지역 문화에 미치는 효과를 읽는 틀이다.",
              "compare": "현실은 단순 동질화보다 혼합과 재구성으로 나타난다는 점을 써야 답이 균형 잡힌다.",
              "example": "맥도날드의 지역화, 외부 문화에 대한 감수성 확대, 다문화가족의 문화 협상이 대표적이다."
            },
            {
              "name": "물건의 사회적 삶",
              "use": "사물이 세계를 어떻게 연결하는지 추적하는 인류학적 접근이다.",
              "compare": "물건을 정적인 소비재가 아니라 생산, 유통, 사용, 폐기 단계를 가진 사회적 존재로 본다.",
              "example": "커피, 초콜릿, 스마트폰, 콜탄 사례는 생산자와 소비자의 연결을 드러낸다."
            }
          ]
        },
        {
          "title": "언어와 권력",
          "items": [
            {
              "name": "생산성 / 전위",
              "use": "인간 언어의 대표적 특징 두 가지다.",
              "compare": "생산성은 제한된 규칙으로 무한한 표현을 만드는 능력, 전위는 지금 여기 없는 대상도 말할 수 있는 능력이다.",
              "example": "인간은 과거 사건이나 미래 계획을 자유롭게 말할 수 있지만 비인간 영장류 소통은 훨씬 제한적이다."
            },
            {
              "name": "침묵 / 제스처 / 신체언어",
              "use": "비구어적 소통도 문화와 권력의 질서 속에서 해석해야 함을 보여 준다.",
              "compare": "같은 침묵이라도 무지, 예의, 복종, 저항으로 다르게 읽힐 수 있다.",
              "example": "서아파치 인디언의 침묵, 쿠웨이트 여성의 머리 가리기, 기모노의 상징 체계가 대표적이다."
            },
            {
              "name": "사피어-워프 / 사회언어학",
              "use": "언어와 문화 관계를 설명하는 두 축이다.",
              "compare": "사피어-워프는 언어가 사고를 형성한다고 보고, 사회언어학은 사회적 맥락과 권력 관계가 언어를 형성한다고 본다.",
              "example": "눈 관련 어휘, 젠더화된 말투, 표준어의 권위는 두 이론을 비교해서 읽을 수 있다."
            },
            {
              "name": "문화 자본 / 위신 언어 / 디지털 행동주의",
              "use": "말하기 방식과 디지털 소통이 자원과 정치적 힘이 될 수 있음을 설명한다.",
              "compare": "문화 자본은 언어 습관이 자산이 되는 과정이고, 디지털 행동주의는 연결망이 정치적 연대로 전환되는 과정이다.",
              "example": "취업 시장의 세련된 말하기, 표준어 중심 교육, 밀크티동맹 해시태그가 여기에 해당한다."
            }
          ]
        },
        {
          "title": "글로벌 경제",
          "items": [
            {
              "name": "근대화 이론 / 종속 이론",
              "use": "개발과 저발전을 설명하는 가장 기본적인 비교 틀이다.",
              "compare": "근대화는 모두가 같은 발전 경로를 간다고 보지만, 종속 이론은 불평등한 세계경제 구조가 저발전을 재생산한다고 본다.",
              "example": "식민주의 이후에도 자원이 많은 국가가 빈곤을 벗어나지 못하는 이유를 종속 이론이 더 잘 설명한다고 쓸 수 있다."
            },
            {
              "name": "중심부 / 준주변부 / 주변부",
              "use": "세계체계 이론의 핵심 범주다.",
              "compare": "누가 고부가가치를 통제하고, 누가 원자재와 값싼 노동력을 제공하는지를 구분한다.",
              "example": "카카오 무역, 참치 시장에서 일본이 가격과 기준을 정하는 사례가 대표적이다."
            },
            {
              "name": "신자유주의 / 케인스주의",
              "use": "국가와 시장의 역할을 둘러싼 경제 철학 비교다.",
              "compare": "신자유주의는 자유 시장과 민영화를 중시하고, 케인스주의는 국가 개입과 안전망을 더 중시한다.",
              "example": "IMF·세계은행의 구조조정 정책과 팬데믹 시기의 적극적 재정 개입을 대비하면 이해가 쉽다."
            },
            {
              "name": "상품 사슬 / 마찰",
              "use": "상품이 생산자에서 소비자에게 이동하는 과정과 그 과정의 갈등을 읽는다.",
              "compare": "상품 사슬이 연결 구조를 보여 준다면, 마찰은 그 연결이 불안정하고 갈등적이라는 점을 드러낸다.",
              "example": "팜유, 카카오, 이주노동, 브로커 문제는 연결과 동시에 갈등이 생기는 마찰의 사례다."
            }
          ]
        },
        {
          "title": "사례 읽기",
          "items": [
            {
              "name": "히잡",
              "use": "문화상대주의, 권력, 인권 기준의 긴장을 함께 읽는 사례다.",
              "compare": "무조건 존중 vs 무조건 비판이 아니라, 행위자의 선택과 구조적 강제를 함께 봐야 한다.",
              "example": "한국에서의 이미지와 이슬람권 여성 당사자의 선택 논리를 함께 써야 균형이 잡힌다."
            },
            {
              "name": "커피 / 초콜릿 / 스마트폰",
              "use": "익숙한 사물을 따라가며 세계화의 연결을 읽는 데 적합하다.",
              "compare": "소비자 입장만 보면 보이지 않던 생산자 노동, 자원 채굴, 유통 구조가 보이기 시작한다.",
              "example": "카카오 농가 빈곤, 콜탄 채굴, 바리스타 임금, 내 지불 가격의 관계를 묻는 식이다."
            },
            {
              "name": "밀크티동맹",
              "use": "디지털 행동주의와 초국가적 연대를 설명하는 최신 사례다.",
              "compare": "온라인 해시태그가 오프라인 시위와 결합할 수 있다는 점이 핵심이다.",
              "example": "홍콩, 태국, 대만, 미얀마의 연대를 통해 디지털 연결이 정치적 힘이 되는 방식을 설명한다."
            }
          ]
        }
      ],
      "studyDrills": [
        {
          "title": "정의 → 비교 → 사례 루틴",
          "body": "이 과목의 대부분의 서술형은 이 세 단계로 풀린다.",
          "bullets": [
            "1문장으로 개념 정의를 쓴다.",
            "비슷한 개념과 어떻게 다른지 1~2문장 비교한다.",
            "강의 속 사례를 붙여 개념이 현실에서 어떻게 드러나는지 설명한다."
          ]
        },
        {
          "title": "비교표 암기 루틴",
          "body": "헷갈리는 이론은 짝으로 묶어 외워야 한다.",
          "bullets": [
            "<code>자문화중심주의 vs 문화상대주의</code>",
            "<code>근대화 이론 vs 종속 이론</code>",
            "<code>사피어-워프 vs 사회언어학</code>",
            "<code>신자유주의 vs 케인스주의</code>"
          ]
        },
        {
          "title": "사례 연결 루틴",
          "body": "강의의 사례를 개념에 붙여 보면서 답안을 훈련한다.",
          "bullets": [
            "히잡 → 문화상대주의, 권력, 인권 논쟁",
            "다문화가족 → 문화교차지역, 협상, 세계화",
            "밀크티동맹 → 디지털 행동주의, 초국가적 연대",
            "카카오·팜유·참치 → 상품 사슬, 세계체계, 마찰"
          ]
        },
        {
          "title": "1분 구술 복습",
          "body": "입으로 설명이 막히면 서술형도 막힌다.",
          "bullets": [
            "\"문화는 무엇인가\"를 30초 안에 설명한다.",
            "\"세계화가 모두에게 같은 혜택을 주지 않는 이유\"를 30초 안에 말한다.",
            "\"언어와 권력이 연결되는 방식\"을 예시와 함께 30초 안에 말한다.",
            "\"글로벌 경제를 설명하는 두 이론 이상\"을 비교하며 1분 안에 말한다."
          ]
        }
      ],
      "lectures": [
        {
          "id": "week2-culture",
          "order": 1,
          "status": "ready",
          "badge": "2주차",
          "type": "core",
          "title": "문화란 무엇인가",
          "source": "[2주차] 문화란 무엇인가.pdf",
          "theme": "문화 / 상대주의 / 권력",
          "summary": "문화 개념의 기초를 잡는 강의다. 문화의 속성, 문화화, 규범·가치·상징, 자문화중심주의와 문화상대주의, 그리고 문화 속 권력과 행위성까지 이후 모든 주차의 언어가 되는 개념들을 다룬다.",
          "narrative": [
            "이 강의의 핵심은 문화를 음식, 전통, 예술 같은 눈에 보이는 산물로만 보지 않는 데 있다. 인류학에서 문화는 사람들의 전체적인 삶의 방식이며, 무엇을 정상이라고 여기고 무엇에 가치를 두며 어떤 상징을 통해 세상을 이해하는지를 포괄한다. 그래서 문화는 관습 목록이 아니라 삶을 조직하는 프레임이다.",
            "강의는 문화를 설명할 때 <code>문화화</code>라는 과정을 강조한다. 인간은 문화를 유전적으로 물려받지 않고 가족, 학교, 친구, 미디어, 종교, 제도를 통해 배운다. 그러므로 문화는 자연적 본성이 아니라 학습되고 체화되는 사회적 산물이라는 점이 중요하다.",
            "또 하나의 큰 축은 평가 방식이다. 자기 기준으로 남을 판단하는 자문화중심주의를 넘어, 먼저 그 문화적 맥락 속에서 이해하려는 문화상대주의가 인류학의 기본 태도다. 하지만 이것이 모든 것을 무비판적으로 승인하라는 뜻은 아니며, 권력과 인권 문제를 함께 읽어야 한다는 점까지 강의가 분명히 짚는다."
          ],
          "concepts": [
            {
              "title": "문화의 속성",
              "body": "문화는 학습되고 가르쳐지며, 공유되는 동시에 변화한다. 또한 상징적이면서 물질적이다. 따라서 문화는 고정된 전통의 보관함이 아니라 사회 속에서 계속 재구성되는 과정이다."
            },
            {
              "title": "문화화",
              "body": "인간은 주변 사람들과 제도를 통해 문화를 배운다. 학교 교육처럼 공식적인 학습도 있고, 가족·친구·미디어를 통한 비공식적이고 무의식적인 학습도 있다."
            },
            {
              "title": "규범 / 가치 / 상징 / 마음의 지도",
              "body": "규범은 기대되는 행동 양식, 가치는 중요하다고 여기는 기준, 상징은 다른 것을 대표하는 기호, 마음의 지도는 세계를 분류하고 이해하는 틀이다. 이 네 요소를 함께 써야 문화 설명이 입체적이 된다."
            },
            {
              "title": "자문화중심주의와 문화상대주의",
              "body": "자문화중심주의는 자기 문화를 보편 기준으로 삼는 태도이고, 문화상대주의는 특정 행동을 그 사회의 역사·환경·관계 속에서 이해하려는 접근이다. 인류학은 후자의 태도를 통해 판단을 잠시 유보하고 맥락을 읽는다."
            },
            {
              "title": "권력 / 헤게모니 / 행위성",
              "body": "권력은 문화 바깥이 아니라 문화 속 규범과 제도에 스며 있다. 헤게모니는 동의와 내면화를 통한 지배를, 행위성은 그 질서에 도전하고 변화를 만들어 낼 수 있는 역량을 뜻한다."
            }
          ],
          "commands": [
            {
              "name": "문화의 속성 정리",
              "syntax": "문화 = 삶의 방식 전체\\n핵심 속성 = 학습됨 / 공유됨 / 변화함 / 상징적이며 물질적",
              "idea": "시험에서 문화를 정의할 때는 좁은 의미의 전통이나 예술이 아니라 사람들의 전체 삶의 방식을 포괄하는 개념으로 설명해야 한다.",
              "example": "벌 유충과 양파 수프 사례는 무엇이 혐오스럽고 무엇이 맛있는지조차 문화마다 다를 수 있음을 보여 준다.",
              "pitfall": "문화를 민족 고유성이나 전통문화 보존 차원으로만 쓰면 인류학적 정의에서 너무 좁아진다."
            },
            {
              "name": "규범 / 가치 / 상징 / 마음의 지도",
              "syntax": "규범 = 어떻게 행동해야 하는가\\n가치 = 무엇이 중요하고 좋은가\\n상징 = 무엇이 무엇을 대표하는가\\n마음의 지도 = 세계를 분류하고 이해하는 틀",
              "idea": "이 네 요소는 문화가 실제로 개인의 사고와 행동을 조직하는 방식을 설명할 때 가장 유용한 세트다.",
              "example": "히잡, 종교 상징, 결혼 규범, 나이·인종 분류 기준은 모두 이 틀을 통해 읽을 수 있다.",
              "pitfall": "규범과 가치를 같은 말처럼 쓰면 답이 흐려진다. 규범은 행동 기대, 가치는 중요성 판단이라는 차이를 분명히 해야 한다."
            },
            {
              "name": "자문화중심주의 vs 문화상대주의",
              "syntax": "자문화중심주의 = 자기 문화를 기준으로 타문화를 판단\\n문화상대주의 = 먼저 그 문화의 맥락 속 의미를 이해",
              "idea": "이 비교는 다문화사회 이해 과목의 가장 기본적인 답안 틀이다.",
              "example": "히잡을 한국 사회의 억압 이미지로만 읽지 않고, 지역·계층·종교·선택의 맥락 속에서 보는 것이 문화상대주의적 접근이다.",
              "pitfall": "문화상대주의를 '무조건 옳다고 인정하는 태도'로 쓰면 틀린다. 이해를 위한 분석 태도와 규범적 승인 여부는 다르다."
            },
            {
              "name": "권력 / 헤게모니 / 행위성",
              "syntax": "권력 = 자원과 규범을 통해 행동과 질서를 형성하는 힘\\n헤게모니 = 동의와 내면화를 통한 지배\\n행위성 = 그 질서에 도전하고 변화시키는 능력",
              "idea": "문화는 단지 공유되는 것만이 아니라 누가 정상성을 정하고 누가 주변화되는지까지 포함한다.",
              "example": "학교가 복장 규범을 집행하면서 동시에 그 규범이 도전받는 공간이 되는 사례, 그리고 일상적 저항은 행위성의 예다.",
              "pitfall": "권력을 경찰, 군대, 법 같은 강제력으로만 쓰면 부족하다. 일상 규범과 자기 규율의 차원까지 써야 한다."
            }
          ],
          "pitfalls": [
            "문화상대주의와 다문화주의를 같은 개념처럼 쓰면 안 된다.",
            "문화상대주의는 설명의 태도이지 무조건적 찬성이 아니다.",
            "권력을 노골적인 강압으로만 설명하면 헤게모니와 자기 규율이 빠진다.",
            "본질주의는 특정 집단의 속성을 자연적이고 고정된 것으로 보는 관점이라는 점을 기억해야 한다."
          ],
          "checklist": [
            "문화를 2문장으로 정의할 수 있다.",
            "규범, 가치, 상징, 마음의 지도를 각각 구분해 설명할 수 있다.",
            "자문화중심주의와 문화상대주의 차이를 사례와 함께 말할 수 있다.",
            "헤게모니와 행위성을 짧게 정의할 수 있다."
          ],
          "quiz": [
            {
              "q": "왜 문화상대주의가 다문화사회를 이해하는 데 중요한가?",
              "a": "자기 문화의 기준으로 타문화를 재단하지 않고, 그 실천이 어떤 역사적·사회적 맥락 속에서 의미를 갖는지 먼저 파악하게 해 주기 때문이다."
            },
            {
              "q": "규범과 가치는 어떻게 다른가?",
              "a": "규범은 기대되는 행동 방식이고, 가치는 그 사회가 중요하다고 여기는 판단 기준이다."
            },
            {
              "q": "헤게모니를 한 문장으로 설명하면?",
              "a": "강압보다 동의와 내면화를 통해 사람들이 특정 질서를 당연하게 받아들이게 만드는 권력의 방식이다."
            }
          ],
          "pages": 29
        },
        {
          "id": "week3-globalization",
          "order": 2,
          "status": "ready",
          "badge": "3주차",
          "type": "core",
          "title": "세계화와 문화",
          "source": "[3주차] 세계화와 문화.pdf",
          "theme": "세계화 / 소비 문화 / 사물의 사회적 삶",
          "summary": "오늘날 세계화의 네 가지 역동성과 문화적 효과를 설명하는 강의다. 소비 문화, 이주, 다문화가족, 세계시민주의, 그리고 커피·초콜릿·스마트폰 같은 사물을 따라가는 인류학적 시선을 함께 다룬다.",
          "narrative": [
            "이 강의는 세계화를 추상적인 '국제화'로 보지 않고, 사람들의 일상과 감각을 재편하는 힘으로 설명한다. 시공간 압축은 거리와 시간 감각을 바꾸고, 유연한 축적은 기업의 생산 방식과 노동 구조를 바꾸며, 이주와 불균등한 발전은 누구에게 연결의 혜택이 돌아가고 누구에게 불이익이 집중되는지를 드러낸다.",
            "중요한 점은 세계화가 문화를 지워 버리기만 하는 것이 아니라 새로운 혼합과 재구성을 만든다는 것이다. 글로벌 브랜드가 지역 취향에 맞게 변형되고, 다문화가족은 서로 다른 생활양식과 가치관을 협상하며 새로운 가족문화를 만든다. 따라서 세계화는 동질화와 혼합, 갈등과 적응이 동시에 일어나는 과정이다.",
            "후반부의 물건의 사회적 삶은 이 강의의 시선을 가장 잘 보여 준다. 커피 한 잔, 초콜릿 한 조각, 스마트폰 한 대를 따라가면 생산자와 소비자, 농촌과 도시, 자원 채굴과 광고, 노동과 취향이 하나의 사슬로 연결되어 있다는 사실이 드러난다."
          ],
          "concepts": [
            {
              "title": "시공간 압축",
              "body": "교통과 통신 기술의 발전으로 거리와 시간에 대한 인간의 감각이 바뀐 현상이다. 이메일, 스마트폰, 고속 교통은 멀리 있는 사람과 장소를 훨씬 가깝게 느끼게 만든다."
            },
            {
              "title": "유연한 축적",
              "body": "기업이 더 싼 노동력, 세금, 규제를 찾아 생산과 유통을 유연하게 옮기며 이윤을 극대화하는 전략이다. 아웃소싱과 오프쇼어링이 대표적이다."
            },
            {
              "title": "불균등한 발전",
              "body": "세계화의 연결이 확대되더라도 혜택은 고르게 배분되지 않는다는 점을 가리킨다. 국적, 계급, 성별, 연령에 따라 접근 가능한 자원과 기회가 다르다."
            },
            {
              "title": "문화교차지역과 다문화가족",
              "body": "서로 다른 문화가 충돌하고 협상하며 적응이 일어나는 지점이다. 국제결혼 가족은 음식, 성역할, 친족 관계를 조정하며 독특한 가족문화를 만들어 간다."
            },
            {
              "title": "물건의 사회적 삶",
              "body": "사물도 생산, 유통, 사용, 폐기의 이력을 가진다는 관점이다. 물건을 따라가면 세계화의 인간적 차원과 숨겨진 연결망이 드러난다."
            }
          ],
          "commands": [
            {
              "name": "세계화의 네 가지 역동",
              "syntax": "1) 시공간 압축\\n2) 유연한 축적\\n3) 증가하는 이주\\n4) 불균등한 발전",
              "idea": "이 네 개를 정확히 묶어 말할 수 있어야 세계화 관련 서술형 답안의 뼈대가 선다.",
              "example": "항공·인터넷은 시공간 압축, 해외 생산 이전은 유연한 축적, 국제결혼과 송금은 이주, 인터넷 접근 격차는 불균등한 발전의 사례다.",
              "pitfall": "세계화를 무조건 '국제 교류 증가' 정도로만 쓰면 강의의 핵심 구조가 빠진다."
            },
            {
              "name": "동질화 vs 혼합",
              "syntax": "동질화 = 글로벌 상품과 규범이 지역 차이를 약화\\n혼합 = 지역 공동체가 외부 요소를 재구성해 새로운 형태를 만듦",
              "idea": "강의는 세계화 결과를 단순 동질화로 보지 않고, 지역 문화의 재구성까지 함께 본다.",
              "example": "맥도날드가 지역의 종교와 입맛에 맞춰 메뉴를 조정하는 사례는 혼합을 보여 준다.",
              "pitfall": "동질화만 강조하면 지역사회의 행위성과 재구성 능력이 사라진다."
            },
            {
              "name": "문화교차지역으로서 다문화가족",
              "syntax": "다문화가족 = 문화 차이가 충돌하거나 협상되는 생활세계\\n핵심 = 적응 / 타협 / 중개 / 재구성",
              "idea": "다문화가족은 추상적 세계화가 가족 생활에서 어떻게 구체화되는지를 보여 주는 사례다.",
              "example": "평소에는 한국식을 먹다가 특별한 날 본국 음식을 차리는 방식은 문화 협상의 전형적 사례다.",
              "pitfall": "다문화가족을 단순히 '두 문화의 공존'으로만 쓰면 협상과 긴장이라는 핵심이 빠진다."
            },
            {
              "name": "물건의 사회적 삶",
              "syntax": "사물 = 창조 / 교환 / 사용 / 폐기의 생애를 가짐\\n질문 = 어디서 왔나 / 누가 만들었나 / 누가 이익을 얻나 / 숨은 비용은 무엇인가",
              "idea": "사물을 따라가면 생산자와 소비자의 연결, 자원 채굴, 노동 조건, 가격 형성의 불평등을 읽을 수 있다.",
              "example": "커피, 초콜릿, 스마트폰, 콜탄 사례는 익숙한 소비재를 낯설게 보게 만든다.",
              "pitfall": "제품의 원산지만 적고 끝내면 안 된다. 노동, 운송, 가격, 환경 비용까지 확장해야 인류학적 질문이 된다."
            }
          ],
          "pitfalls": [
            "세계화를 무조건 진보나 개방으로만 설명하면 불균등한 발전이 빠진다.",
            "동질화와 혼합은 둘 중 하나만 일어나는 것이 아니라 긴장 속에서 함께 나타날 수 있다.",
            "다문화가족 사례는 문화 차이 나열보다 협상 과정에 초점을 맞춰야 한다.",
            "사물의 사회적 삶은 원산지 맞히기 문제가 아니라 연결망 추적의 관점이다."
          ],
          "checklist": [
            "세계화의 네 가지 역동을 순서대로 말할 수 있다.",
            "동질화와 혼합의 차이를 설명할 수 있다.",
            "다문화가족을 문화교차지역으로 설명할 수 있다.",
            "커피나 스마트폰을 예로 들어 사물의 사회적 삶 질문을 만들 수 있다."
          ],
          "quiz": [
            {
              "q": "왜 세계화의 핵심을 '연결'만으로 설명하면 부족한가?",
              "a": "연결은 확대되지만 혜택과 접근은 불균등하게 분배되며, 그 과정에서 종속과 격차, 갈등이 함께 커지기 때문이다."
            },
            {
              "q": "물건의 사회적 삶이 보여 주는 것은 무엇인가?",
              "a": "익숙한 소비재가 사실은 생산자, 운반자, 판매자, 소비자, 자원 채굴 현장까지 이어지는 복잡한 세계적 연결망 속에 있다는 점이다."
            },
            {
              "q": "다문화가족을 세계화와 연결해서 설명하면?",
              "a": "세계적 이동과 문화 접촉이 가족 단위 생활세계에서 음식, 성역할, 친족 관계, 정체성 협상으로 구체화되는 문화교차지역의 사례다."
            }
          ],
          "pages": 27
        },
        {
          "id": "week4-language",
          "order": 3,
          "status": "ready",
          "badge": "4주차",
          "type": "core",
          "title": "언어와 소통",
          "source": "[4주차] 언어와 소통.pdf",
          "theme": "언어 / 비구어 / 권력 / 디지털",
          "summary": "언어를 말과 글의 좁은 영역이 아니라 권력과 불평등, 신체와 디지털 기술까지 포함하는 소통 체계로 보는 강의다. 인간 언어의 특징, 침묵과 제스처, 언어와 문화의 이론, 문화 자본, 디지털 행동주의가 이어진다.",
          "narrative": [
            "이 강의는 언어를 단순한 정보 전달 도구가 아니라 사회적 행위로 이해하게 만든다. 인간은 발화와 문자뿐 아니라 수어, 제스처, 침묵, 신체 표식, 의복을 통해 의미를 주고받는다. 따라서 소통은 말만의 문제가 아니라 문화적으로 학습된 상징 체계 전체의 문제다.",
            "중간 부분에서 강의는 언어와 문화 관계를 두 갈래로 설명한다. 사피어-워프 가설은 언어가 사고를 형성한다고 보고, 사회언어학은 사회적 맥락과 권력 관계가 언어의 의미와 사용을 만든다고 본다. 시험에서는 둘을 대립시키기보다 초점의 차이로 설명하면 안정적이다.",
            "후반부는 언어를 권력과 자원의 관점에서 읽는다. 특정 말하기 방식이 위신을 갖고, 그 위신이 취업과 임금, 교육 성취로 이어질 때 언어는 문화 자본이 된다. 동시에 디지털 플랫폼은 소통 방식을 바꾸고 정치적 행동주의와 초국가적 연대를 가능하게 하지만, 디지털 격차와 혐오 확산이라는 한계도 함께 남긴다."
          ],
          "concepts": [
            {
              "title": "인간 언어의 특징",
              "body": "생산성은 제한된 규칙으로 무한한 표현을 만드는 능력이고, 전위는 지금 여기 없는 대상과 시간도 말할 수 있는 능력이다. 인간 언어는 이 점에서 비인간 영장류의 소통과 구별된다."
            },
            {
              "title": "비구어적 소통",
              "body": "제스처, 침묵, 시선, 자세, 의복, 신체 변형은 모두 의미를 전달하는 체계다. 비구어도 문화적으로 학습되며 권력과 지위의 차이를 반영한다."
            },
            {
              "title": "사피어-워프와 사회언어학",
              "body": "사피어-워프는 언어가 세계 인식과 사고를 형성한다고 보고, 사회언어학은 계급, 젠더, 인종/종족, 권력 같은 사회적 맥락이 언어를 형성한다고 본다."
            },
            {
              "title": "문화 자본과 위신 언어",
              "body": "특정 언어 습관과 말하기 방식은 사회적으로 더 높은 가치와 권위를 부여받는다. 이때 언어는 취업, 임금, 교육 제도에서 작동하는 문화 자본이 된다."
            },
            {
              "title": "디지털 시대의 소통",
              "body": "디지털 네이티브와 디지털 이민자, 디지털 격차, 디지털 행동주의는 기술이 소통 방식을 어떻게 바꾸는지 보여 준다. 밀크티동맹은 온라인 해시태그가 초국가적 정치 연대로 확장되는 사례다."
            }
          ],
          "commands": [
            {
              "name": "언어의 범위 확장",
              "syntax": "언어 = 학습되고 공유된 상징과 기호 체계\\n소통 = 말 + 글 + 수어 + 제스처 + 침묵 + 신체언어 + 디지털 기호",
              "idea": "이 강의에서 언어는 좁은 문법 지식이 아니라, 의미를 주고받는 문화적 기호 체계 전체로 이해해야 한다.",
              "example": "수어, 인사 제스처, 시선 처리, 의복 코드, 해시태그는 모두 사회적으로 학습된 소통 방식이다.",
              "pitfall": "언어를 구어와 문자에만 한정하면 침묵, 제스처, 신체언어 사례를 설명할 수 없다."
            },
            {
              "name": "침묵과 권력",
              "syntax": "침묵 = 결핍이 아니라 사회적 지위와 권력 관계 속에서 의미를 갖는 비구어적 소통",
              "idea": "침묵은 말하지 못함이 아니라, 상황에 따라 예절·권위·거리·저항을 표현하는 방식일 수 있다.",
              "example": "서아파치 인디언의 침묵, 시베리아 농촌의 며느리, 법정에서 판사의 적은 발화는 모두 다른 맥락의 침묵이다.",
              "pitfall": "침묵을 지성 부족이나 감정 결핍으로 해석하면 자문화중심주의적 오해가 된다."
            },
            {
              "name": "사피어-워프 vs 사회언어학",
              "syntax": "사피어-워프 = 언어가 사고를 형성\\n사회언어학 = 사회적 맥락과 권력이 언어 사용을 형성",
              "idea": "둘 다 언어와 문화의 관계를 설명하지만, 하나는 인식 구조를, 다른 하나는 사회적 맥락과 권력 관계를 더 강조한다.",
              "example": "눈 관련 어휘와 세계 인식은 사피어-워프 쪽, 젠더화된 말투와 표준어의 위상은 사회언어학 쪽 설명에 가깝다.",
              "pitfall": "사피어-워프를 극단적 언어결정론으로만 단순화하면 현대 인류학의 실제 수용 방식과 어긋난다."
            },
            {
              "name": "문화 자본 / 위신 언어",
              "syntax": "문화 자본 = 언어 습관·태도·말하기 방식이 사회적 자산이 되는 것\\n위신 언어 = 부·성공·교육·권력과 연결된 말하기 방식",
              "idea": "언어는 단지 소통 도구가 아니라 사회적 이동성과 평가의 기준이 될 수 있다.",
              "example": "표준어, 세련된 어휘, 자신감 있는 말투가 채용과 교육 제도에서 더 높은 가치를 갖는 현상이 여기에 해당한다.",
              "pitfall": "개인의 말하기 능력만의 문제로 보면 안 되고, 어떤 언어 형태가 더 정당하고 우월한 것으로 인정되는 사회 구조를 함께 봐야 한다."
            },
            {
              "name": "디지털 격차 / 디지털 행동주의",
              "syntax": "디지털 격차 = 접근성과 연결성의 불균형\\n디지털 행동주의 = 디지털 플랫폼을 통한 정치적 연대와 행동",
              "idea": "디지털 기술은 연결과 참여의 기회를 넓히지만, 그 기회는 불균등하게 분배되고 감시와 혐오 문제도 동반한다.",
              "example": "밀크티동맹은 트위터 해시태그가 홍콩, 태국, 대만, 미얀마의 민주화 연대로 확장된 사례다.",
              "pitfall": "디지털 행동주의를 무조건 민주적 진보로만 보면 안 된다. 휘발성, 감시, 혐오 확산, 접근성 차이를 함께 써야 한다."
            }
          ],
          "pitfalls": [
            "언어를 말과 문자만으로 한정하면 강의의 핵심이 사라진다.",
            "침묵을 해석할 때는 권력과 상황을 함께 봐야 한다.",
            "언어와 젠더 관계를 보편적 법칙처럼 쓰면 비교문화적 다양성을 놓친다.",
            "디지털 연결이 곧 평등한 참여를 의미하는 것은 아니다."
          ],
          "checklist": [
            "생산성과 전위를 설명할 수 있다.",
            "침묵이 권력과 연결되는 사례를 말할 수 있다.",
            "사피어-워프와 사회언어학의 차이를 비교할 수 있다.",
            "문화 자본과 위신 언어를 정의할 수 있다.",
            "밀크티동맹을 디지털 행동주의 사례로 설명할 수 있다."
          ],
          "quiz": [
            {
              "q": "왜 침묵을 단순한 무지나 결핍으로 보면 안 되는가?",
              "a": "침묵은 문화마다 예절, 지위, 친밀성, 권위, 저항을 표현하는 의미 있는 소통 행위일 수 있기 때문이다."
            },
            {
              "q": "문화 자본을 언어와 연결해 설명하면?",
              "a": "특정 언어 습관과 말하기 방식이 사회적으로 더 높은 가치와 정당성을 인정받아 취업, 교육, 임금 같은 자원으로 전환되는 것이다."
            },
            {
              "q": "밀크티동맹이 중요한 이유는?",
              "a": "해시태그 같은 디지털 기호가 초국가적 정치 연대와 오프라인 시위 동력으로 연결될 수 있음을 보여 주기 때문이다."
            }
          ],
          "pages": 29
        },
        {
          "id": "week5-global-economy",
          "order": 4,
          "status": "ready",
          "badge": "5주차",
          "type": "core",
          "title": "글로벌 경제",
          "source": "[5주차] 글로벌 경제.pdf",
          "theme": "개발 / 종속 / 세계체계 / 신자유주의",
          "summary": "세계경제를 설명하는 주요 이론과 조직 원리를 정리하는 강의다. 근대화 이론, 종속 이론, 세계체계 이론, 신자유주의, 상품 사슬과 마찰을 카카오·참치·팜유·이주노동 사례와 연결해 읽는다.",
          "narrative": [
            "이 강의는 '내가 먹는 초콜릿은 어디에서 오는가'라는 질문에서 시작해, 일상적 소비가 얼마나 거대한 세계경제 구조와 연결되어 있는지 보여 준다. 카카오와 코트디부아르 사례는 세계경제가 단순한 교환이 아니라 식민주의의 흔적, 자원 이동, 빈곤의 재생산까지 포함하는 복합 구조임을 드러낸다.",
            "중간부의 핵심은 이론 비교다. 근대화 이론은 모두가 같은 발전 궤적을 따를 수 있다고 보지만, 종속 이론은 세계경제의 불평등한 구조가 저발전을 재생산한다고 본다. 세계체계 이론은 이를 중심부·준주변부·주변부 구도로 정리해, 누가 고부가가치와 금융을 통제하고 누가 원자재와 노동력을 제공하는지 보여 준다.",
            "후반부는 국가와 시장의 관계, 그리고 실제 상품 이동의 현장으로 내려간다. 신자유주의는 자유 시장과 민영화를 강조하고, 케인스주의는 국가 개입과 안전망을 중시한다. 상품 사슬과 애나 칭의 마찰 개념은 이러한 거시 구조가 현장에서 왜 혼란스럽고 갈등적이며 불평등한 만남으로 나타나는지 설명해 준다."
          ],
          "concepts": [
            {
              "title": "근대화 이론과 개발",
              "body": "식민주의 이후 저개발 국가도 산업화 국가와 같은 경로를 따라 생활 수준을 높일 수 있다고 본다. 개발은 이를 위해 인프라 투자와 제도 개혁을 추진한 전략이다."
            },
            {
              "title": "종속 이론과 신식민주의",
              "body": "식민주의가 끝나도 불평등한 경제 관계는 지속된다고 본다. 저발전은 내부 결핍이 아니라 세계경제에 종속된 참여 방식 때문에 재생산된다는 시각이다."
            },
            {
              "title": "세계체계 이론",
              "body": "중심부, 준주변부, 주변부라는 위치를 통해 세계경제를 설명한다. 중심부는 고부가가치와 금융을 통제하고, 주변부는 원자재와 값싼 노동력을 제공한다."
            },
            {
              "title": "신자유주의와 케인스주의",
              "body": "신자유주의는 자유 시장과 민영화, 정부 역할 축소를 강조한다. 케인스주의는 공공 투자와 규제, 안전망을 통해 자본주의의 극단적 결과를 완화하려 한다."
            },
            {
              "title": "상품 사슬과 마찰",
              "body": "상품 사슬은 재료 채취부터 최종 소비까지 이어지는 네트워크이고, 마찰은 그 연결이 현장에서 갈등과 불평등을 동반하는 과정을 뜻한다."
            }
          ],
          "commands": [
            {
              "name": "근대화 이론 vs 종속 이론",
              "syntax": "근대화 이론 = 모든 국가는 비슷한 발전 경로를 따를 수 있음\\n종속 이론 = 세계경제의 불평등한 구조가 저발전을 재생산함",
              "idea": "이 두 이론의 차이는 '가난의 원인을 내부의 미발전으로 볼 것인가, 구조적 종속으로 볼 것인가'에 있다.",
              "example": "식민주의 이후에도 자원 부국이 빈곤을 벗어나지 못한 현실은 종속 이론의 문제의식을 잘 보여 준다.",
              "pitfall": "근대화 이론을 '무조건 틀린 이론'처럼 쓰기보다, 무엇을 전제하는지와 어떤 한계가 비판받았는지를 써야 한다."
            },
            {
              "name": "중심부 / 준주변부 / 주변부",
              "syntax": "중심부 = 고부가가치와 금융 통제\\n준주변부 = 중간 위치에서 자원과 제조를 연결\\n주변부 = 원자재·값싼 노동력 공급",
              "idea": "세계체계 이론은 국가 간 위계를 공간적 지도처럼 읽게 해 준다.",
              "example": "카카오 무역에서 중심부 기업이 가격과 가공을 통제하고, 주변부 농가는 원재료 공급과 저소득을 떠안는 구조가 전형적이다.",
              "pitfall": "중심부와 주변부가 반드시 나라 전체와 1:1로 대응되는 것은 아니다. 주변부 국가 내부에도 중심부 지역이 존재할 수 있다."
            },
            {
              "name": "신자유주의 vs 케인스주의",
              "syntax": "신자유주의 = 자유 시장 / 민영화 / 규제 완화 / 정부 축소\\n케인스주의 = 공공 투자 / 안전망 / 규제 / 경기 조절을 위한 국가 개입",
              "idea": "국가와 시장의 관계를 어떻게 볼 것인가를 비교하는 틀이다.",
              "example": "IMF 구조조정은 신자유주의적 흐름, 팬데믹 시기의 대규모 재정 지출과 공공 투자 확대는 케인스주의적 대응으로 읽을 수 있다.",
              "pitfall": "둘을 단순히 '정부 많음 vs 적음'으로만 쓰면 부족하다. 어떤 사회적 결과를 낳는지도 써야 한다."
            },
            {
              "name": "상품 사슬",
              "syntax": "재료 채취 → 부품 제조 → 조립 → 유통 → 최종 소비\\n질문 = 누가 만들고 누가 통제하며 누가 이익을 얻는가",
              "idea": "상품 사슬은 소비자와 생산자의 거리를 좁혀, 일상적 소비가 세계경제의 어떤 노동과 자원을 밟고 있는지 보게 한다.",
              "example": "초콜릿, 참치, 스마트폰, 팜유는 모두 상품 사슬 추적에 적합한 사례다.",
              "pitfall": "국가 간 이동만 나열하면 안 된다. 가격 결정, 기준 설정, 숨은 비용, 노동 조건을 함께 봐야 한다."
            },
            {
              "name": "마찰",
              "syntax": "마찰 = 세계적 연결이 현장에서 만들어 내는 갈등, 혼란, 불평등한 상호작용",
              "idea": "세계경제의 연결은 매끄럽지 않으며, 지역사회·기업·정부·NGO·이주 브로커가 얽힌 긴장 속에서 전개된다.",
              "example": "인도네시아 팜유 개발, 열대우림 파괴, 이주노동자 브로커 문제는 모두 세계적 연결의 마찰을 보여 준다.",
              "pitfall": "마찰을 단순히 갈등이라고만 쓰면 부족하다. 서로 다른 위치의 행위자들이 한 사슬 안에서 불균등하게 만나는 구조를 강조해야 한다."
            }
          ],
          "pitfalls": [
            "발전과 개발을 무조건 긍정적 단어로만 쓰면 안 된다. 누가 기준을 정하는지 봐야 한다.",
            "종속 이론은 단순히 '가난한 나라가 불쌍하다'가 아니라 구조적 관계 분석이다.",
            "세계체계 이론에서 중심부와 주변부는 고정된 지리적 상자처럼만 보면 안 된다.",
            "신자유주의 비판은 시장 자체가 아니라 불평등한 효과와 국가 역할 축소의 문제를 다룬다."
          ],
          "checklist": [
            "근대화 이론과 종속 이론 차이를 설명할 수 있다.",
            "중심부·준주변부·주변부를 예시와 함께 말할 수 있다.",
            "신자유주의와 케인스주의를 비교할 수 있다.",
            "상품 사슬과 마찰 개념을 사례에 적용할 수 있다."
          ],
          "quiz": [
            {
              "q": "왜 카카오 사례가 세계경제를 설명하는 데 적합한가?",
              "a": "생산국 농가, 수출 구조, 식민주의의 흔적, 가격 통제, 소비국 기업의 이윤이 하나의 사슬로 연결되어 세계경제의 불평등한 구조를 보여 주기 때문이다."
            },
            {
              "q": "세계체계 이론에서 주변부는 무엇을 제공하는가?",
              "a": "원자재, 값싼 노동력, 그리고 중심부 경제 활동을 위한 시장을 제공한다."
            },
            {
              "q": "마찰 개념이 중요한 이유는?",
              "a": "세계적 연결이 실제 현장에서는 갈등, 불안정, 불평등한 만남으로 나타난다는 점을 드러내기 때문이다."
            }
          ],
          "pages": 26
        },
        {
          "id": "cultural-relativism-reading",
          "order": 5,
          "status": "ready",
          "badge": "읽기자료",
          "type": "practice",
          "title": "낯선 곳에서 나를 만나다",
          "source": "문화상대주의_낯선곳에서 나를 만나다.pdf",
          "theme": "문화상대주의 / 낯설게 보기 / 해석",
          "summary": "문화상대주의를 개념으로만 설명하지 않고 실제 읽기 사례로 보여 주는 보충 강의다. 로라 보해넌의 '티브족, 셰익스피어를 만나다'와 호러스 마이너의 '나시리마 사람들'을 통해, 익숙한 것도 문화가 다르면 전혀 다르게 해석되며 설명 방식 자체가 타문화를 낯설게 만들 수 있음을 배운다.",
          "narrative": [
            "이 읽기자료의 핵심은 '문화상대주의는 타문화를 봐주는 태도'가 아니라, 내가 당연하다고 믿는 해석 방식 자체를 의심하게 만드는 훈련이라는 점이다. 앞부분에서 저자는 인류학자도 자기 문화의 산물이며, 다른 문화를 이해하려면 자기 기준의 보편성을 내려놓아야 한다고 말한다. 그래서 문화상대주의는 도덕 판단을 멈추자는 선언이 아니라, 먼저 맥락 속에서 이해하자는 해석의 원칙이다.",
            "로라 보해넌의 글에서 이 원칙은 아주 생생하게 드러난다. 보해넌은 티브족 장로들에게 <code>햄릿</code> 이야기를 들려주지만, 장로들은 영국식 줄거리를 그대로 받아들이지 않는다. 그들은 자기들의 친족 체계, 상속 규칙, 재혼 관습, 마법과 악령에 대한 믿음을 기준으로 이야기를 다시 해석한다. 죽은 왕 다음에 아들이 아니라 남동생이 대추장이 되는 것, 왕의 동생이 형의 아내와 결혼하는 것이 자연스러운 것, 귀신보다는 마법이나 악령 개념으로 사건을 이해하는 것이 모두 그 예다. 이 장면은 '보편적인 이야기'라고 여겼던 <code>햄릿</code>조차 문화에 따라 다르게 읽힌다는 사실을 보여 준다.",
            "호러스 마이너의 <code>나시리마 사람들</code>은 반대로 너무 익숙한 문화를 낯설게 보게 만든다. 나시리마는 사실 American을 거꾸로 쓴 말이고, 글에 나오는 의례는 미국인의 욕실, 치과, 병원, 미용, 출산, 몸 관리 같은 일상이다. 그런데 저자는 그것을 마치 기이한 부족의 주술 의례처럼 묘사한다. 이 장치는 설명 언어가 얼마나 강한 힘을 갖는지 드러낸다. 결국 두 글은 같은 결론으로 모인다. 문화를 이해한다는 것은 행동만 보는 것이 아니라, 그 행동을 둘러싼 의미 체계와 설명 방식까지 함께 읽는 일이다."
          ],
          "concepts": [
            {
              "title": "문화상대주의는 해석의 방법이다",
              "body": "문화상대주의는 '다 맞다'는 선언이 아니라, 어떤 행동이나 이야기의 의미를 그 사회의 친족, 역사, 규범, 믿음 속에서 먼저 이해하려는 방법이다."
            },
            {
              "title": "보편성의 환상",
              "body": "우리는 사랑, 가족, 상속, 도덕, 비극 같은 것이 어디서나 비슷하게 이해될 것이라 믿기 쉽다. 하지만 보해넌의 사례는 이런 믿음이 문화적으로 구성된 것임을 보여 준다."
            },
            {
              "title": "문화번역과 오해",
              "body": "타문화를 설명할 때 사람들은 익숙한 자기 언어와 개념으로 번역한다. 그 과정에서 의미가 옮겨지기도 하지만, 동시에 큰 오해와 재해석이 생기기도 한다."
            },
            {
              "title": "낯설게 보기",
              "body": "마이너의 나시리마 글은 너무 익숙한 미국 중산층의 몸 관리 문화를 의도적으로 낯설게 묘사한다. 이를 통해 '미개함'처럼 보이는 판단이 얼마나 설명 방식에 좌우되는지 드러낸다."
            },
            {
              "title": "서술 방식과 권력",
              "body": "타문화를 어떤 말로 부르는가, 무엇을 강조하는가, 무엇을 숨기는가는 중립적이지 않다. 인류학의 글쓰기 방식도 권력과 시선을 담고 있기 때문에 자기반성이 필요하다."
            }
          ],
          "commands": [
            {
              "name": "문화상대주의의 정확한 뜻",
              "syntax": "문화상대주의 = 타문화를 그 사회의 맥락 속에서 먼저 이해하려는 해석 원칙\\n주의 = 무조건 찬성하거나 도덕 판단을 포기한다는 뜻은 아님",
              "idea": "이 자료는 문화상대주의를 추상적 정의가 아니라 실제 오해와 재해석 사례를 통해 보여 준다.",
              "example": "티브족 장로들은 햄릿을 자기 사회의 친족 제도와 마법 관념 속에서 이해했고, 그 과정에서 보해넌의 '원래 의미'는 전혀 자명하지 않게 되었다.",
              "pitfall": "문화상대주의를 윤리적 무비판 승인으로 쓰면 틀린다. 핵심은 이해의 출발점을 바꾸는 데 있다."
            },
            {
              "name": "티브족이 햄릿을 다시 읽는 방식",
              "syntax": "질문 = 이 이야기는 우리 사회 규범으로 보면 어떻게 이해되는가?\\n핵심 축 = 상속 / 재혼 / 친족 / 귀신보다 마법·악령 / 권위 있는 장로의 해석",
              "idea": "보해넌의 글은 하나의 텍스트도 독자의 문화적 배경에 따라 완전히 다르게 해석될 수 있음을 보여 준다.",
              "example": "왕이 죽은 뒤 남동생이 권력을 잇는 것이 자연스럽고, 형의 아내와 동생의 결혼도 이상하지 않다는 해석은 티브족의 질서에 기반한 것이다.",
              "pitfall": "이 사례를 '티브족이 햄릿을 오독했다'고 쓰면 안 된다. 글의 핵심은 오독 비웃기가 아니라 해석의 문화적 상대성이다."
            },
            {
              "name": "나시리마 사람들의 장치",
              "syntax": "낯설게 보이게 묘사된 부족 문화 = 사실은 미국인의 일상\\n핵심 장치 = 익숙한 행위를 주술 의례처럼 재서술",
              "idea": "마이너는 언어만 바꿔도 익숙한 사회가 얼마나 기괴하게 보일 수 있는지 보여 준다.",
              "example": "욕실, 약장, 치과, 병원, 미용, 출산 같은 일상이 '의례', '주술', '전문가의 처치'라는 표현 속에서 낯선 부족 관습처럼 읽힌다.",
              "pitfall": "이 글을 단순 풍자문으로만 보면 부족하다. 시험에서는 설명 언어와 관찰자의 시선이 판단을 어떻게 만든다는 점까지 써야 한다."
            },
            {
              "name": "서술형 답안 틀",
              "syntax": "정의 = 문화상대주의는 맥락 속 이해의 태도다\\n사례 = 티브족의 햄릿 재해석 또는 나시리마의 낯설게 보기\\n의미 = 보편성 환상과 자문화중심주의를 흔든다",
              "idea": "이 자료는 개념 정의와 사례 적용을 한 번에 연결하기 좋다.",
              "example": "보해넌은 문화상대주의가 왜 필요한지 보여 주고, 마이너는 자문화중심주의가 설명 방식에 숨어 있음을 드러낸다.",
              "pitfall": "사례만 길게 쓰고 결론을 안 적으면 점수가 약하다. 반드시 '왜 이 사례가 문화상대주의를 보여 주는가'를 마무리로 써야 한다."
            }
          ],
          "pitfalls": [
            "문화상대주의를 '무조건 다 존중'으로 쓰면 안 된다.",
            "티브족 사례를 원작 오해나 지식 부족으로만 보면 이 읽기자료의 핵심을 놓친다.",
            "나시리마 글을 단순히 웃긴 반전으로만 처리하면 설명 언어의 권력을 놓치게 된다.",
            "인류학자의 설명도 중립적이지 않으며 자기 문화의 시선이 들어간다는 점을 기억해야 한다."
          ],
          "checklist": [
            "문화상대주의와 자문화중심주의 차이를 사례와 함께 설명할 수 있다.",
            "티브족 장로들이 햄릿을 왜 다르게 이해했는지 말할 수 있다.",
            "나시리마가 실제로 무엇을 가리키는지 설명할 수 있다.",
            "낯설게 보기 전략이 왜 인류학적으로 중요한지 한 문장으로 정리할 수 있다."
          ],
          "quiz": [
            {
              "q": "왜 보해넌의 햄릿 이야기는 문화상대주의를 설명하는 대표 사례가 되는가?",
              "a": "같은 이야기도 독자의 친족 제도, 상속 관념, 종교와 마법 관념에 따라 전혀 다른 의미로 해석될 수 있음을 보여 주기 때문이다."
            },
            {
              "q": "나시리마 사람들 글의 핵심 장치는 무엇인가?",
              "a": "익숙한 미국인의 몸 관리와 의료 문화를 낯선 부족 의례처럼 묘사해, 설명 언어가 타문화를 어떻게 기괴하게 만들 수 있는지 보여 주는 것이다."
            },
            {
              "q": "이 읽기자료를 통해 자문화중심주의를 어떻게 비판할 수 있는가?",
              "a": "내가 당연하다고 여기는 가족, 도덕, 몸, 의례, 이야기 해석 방식이 결코 보편적이지 않으며, 타문화를 이해하려면 먼저 자기 기준의 특수성을 자각해야 한다고 말할 수 있다."
            }
          ],
          "pages": 19
        }
      ]
    }
  ]
};
