#!/usr/bin/env python3

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from build_transcript_data import write_transcript_output
from content_workflow import (
    OUTPUT_FILE,
    describe_source_file,
    get_course_lectures_dir,
    get_course_site_file,
    get_source_stat_labels,
    list_source_files,
    load_json,
    make_draft_lecture,
    natural_key,
    normalize_source_name,
    resolve_course_dirs,
    slugify,
    validate_lecture_data,
    validate_site_data,
)


def build_course_payload(course_dir: Path, generated_at: str) -> dict:
    site_file = get_course_site_file(course_dir)
    if not site_file.exists():
        raise SystemExit(f"공통 데이터 파일이 없습니다: {site_file}")

    site_data = load_json(site_file)
    site_errors = validate_site_data(site_data, course_id=course_dir.name)
    if site_errors:
        raise SystemExit("site.json 검증 실패:\n- " + "\n- ".join(site_errors))

    source_folder = Path(site_data["meta"]["sourceFolder"]).expanduser()
    if not source_folder.exists():
        raise SystemExit(f"소스 폴더가 없습니다: {source_folder}")

    public_meta = {key: value for key, value in site_data["meta"].items() if key != "sourceFolder"}

    source_paths = list_source_files(site_data["meta"])
    sources = [describe_source_file(path, source_folder) for path in source_paths]
    metric_by_file = {entry["file"]: entry["metric"] for entry in sources}
    metric_label_by_file = {entry["file"]: entry["metricLabel"] for entry in sources}
    name_by_file = {entry["file"]: entry["name"] for entry in sources}
    type_by_file = {entry["file"]: entry["type"] for entry in sources}
    source_order = {entry["file"]: index for index, entry in enumerate(sources, start=1)}
    stats_source_count_label, stats_source_measure_label = get_source_stat_labels(site_data["meta"], sources)
    source_measure_total = sum(entry["metric"] for entry in sources)

    lectures_dir = get_course_lectures_dir(course_dir)
    authored_lectures = []
    lecture_files = sorted(
        [
            path
            for path in lectures_dir.glob("*.json")
            if not path.name.startswith("_") and not path.name.startswith(".")
        ],
        key=lambda path: natural_key(path.name),
    )

    for lecture_path in lecture_files:
        lecture = load_json(lecture_path)
        lecture["source"] = normalize_source_name(lecture.get("source", ""))
        errors = validate_lecture_data(
            lecture,
            file_name=str(Path("content/courses") / course_dir.name / "lectures" / lecture_path.name),
        )
        if errors:
            raise SystemExit("강의 JSON 검증 실패:\n- " + "\n- ".join(errors))

        lecture.setdefault("status", "ready")
        lecture.setdefault("type", "core")
        lecture.setdefault("order", source_order.get(lecture.get("source", ""), len(authored_lectures) + 1))
        lecture["pages"] = metric_by_file.get(lecture.get("source", ""), 0)
        lecture["sourceMetricLabel"] = metric_label_by_file.get(lecture.get("source", ""), "")
        lecture.setdefault("sourceDisplay", name_by_file.get(lecture.get("source", ""), lecture.get("source", "")))
        lecture["sourceType"] = type_by_file.get(lecture.get("source", ""), "")

        if lecture.get("source") not in metric_by_file:
            lecture["status"] = "missing-source"

        authored_lectures.append(lecture)

    authored_sources = {lecture["source"] for lecture in authored_lectures}
    draft_lectures = [
        make_draft_lecture(source_entry, source_order[source_entry["file"]])
        for source_entry in sources
        if source_entry["file"] not in authored_sources
    ]

    lectures = authored_lectures + draft_lectures
    lectures.sort(
        key=lambda lecture: (
            lecture.get("order", 10_000),
            source_order.get(lecture.get("source", ""), 10_000),
            lecture.get("title", "").lower(),
        )
    )

    return {
        "id": course_dir.name,
        **site_data,
        "meta": {
            **public_meta,
            "courseId": course_dir.name,
            "statsSourceCountLabel": stats_source_count_label,
            "statsSourceMeasureLabel": stats_source_measure_label,
            "sourceMeasureTotal": source_measure_total,
            "sources": sources,
            "generatedAt": generated_at,
            "authoredLectureCount": len(authored_lectures),
            "draftLectureCount": len(draft_lectures),
        },
        "lectures": lectures,
    }


def main() -> int:
    generated_at = datetime.now(timezone.utc).isoformat()
    course_dirs = resolve_course_dirs()
    courses = [build_course_payload(course_dir, generated_at) for course_dir in course_dirs]

    payload = {
        "generatedAt": generated_at,
        "courseOrder": [course["id"] for course in courses],
        "courses": courses,
    }

    output = (
        "/* This file is generated by scripts/build-study-data.py. */\n"
        "/* Do not edit this file directly; edit content/courses/* instead. */\n"
        f"window.studyLibrary = {json.dumps(payload, ensure_ascii=False, indent=2)};\n"
    )
    OUTPUT_FILE.write_text(output, encoding="utf-8")
    transcript_courses = write_transcript_output(course_dirs, generated_at)

    print(f"Built {OUTPUT_FILE.name}")
    print("Built transcript-data.js")
    print(f"- Courses scanned: {len(courses)}")
    print(f"- Transcript courses: {len(transcript_courses)}")

    for course in courses:
        print(
            f"- {course['id']}: sources {len(course['meta']['sources'])}, "
            f"authored {course['meta']['authoredLectureCount']}, "
            f"draft {course['meta']['draftLectureCount']}"
        )

        if course["meta"]["draftLectureCount"] > 0:
            print("  Draft needed:")
            for lecture in course["lectures"]:
                if lecture["status"] != "draft":
                    continue
                suggested = slugify(Path(lecture["source"]).stem) + ".json"
                print(f"  - {lecture['source']} -> {suggested}")

        missing_sources = [lecture for lecture in course["lectures"] if lecture["status"] == "missing-source"]
        if missing_sources:
            print("  Missing source file:")
            for lecture in missing_sources:
                print(f"  - {lecture['source']}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
